README.md
docs/get_started.md

This PR introduces a `README.md` and `docs` directory to organize documentation for development and operational purposes and closes #1

Add documentation to Get Started in development

---

backend/services/permission.py

The API has changed slightly and we are now raising permission errors. Additional tests should be added in the future enforcing these checks.

Fix failing permission service test

---

backend/api/profile.py
backend/services/user.py

This PR aims to do two things:
1. Add documentation to the profile editing routes
2. Refactor the user service to be more idiomatic
The latter is toward the end of this service being used as an example for developers to use as reference. Whereas the profile service endpoints expect the authenticated user to be the same as the user being created/updated in the user service, this service is more useful if we make it work more generally and idiomatically. The _subject_ is the user attempting to carry out the action and the _user_ is the resource the action applies to. This is the more common case developers will experience in features: _subject_ and _resource_ as two separate concerns. When profile editing, it's a special edge case where they are the same.

Refactor backend user service to be idiomatic

---

backend/api/profile.py
backend/services/user.py

Factored out separate create vs. update methods.
Made the signature of create and update in the user service idiomatic (subject first, user model second) and improved permission check to have both feature-specific rule (a user can edit their own profile), as well as administrative permission check.

Refactor backend user service to be idiomatic and documented (#24)

---

backend/api/authentication.py

When performing delegated authentication, the origin host is passed
as a query parameter. This is then used to redirect the user back to
the correct page after authentication. However, in production, the
origin host was not being passed correctly, and the user was being
redirected back to the production hostname.

Fix redirect bug in production authentication

---

alembic.ini
backend/api/authentication.py
backend/entities/user_entity.py
backend/migrations/README
backend/migrations/env.py
backend/migrations/script.py.mako
backend/migrations/versions/48c0ecafd25a_add_github_columns_to_user_table.py
backend/models/user.py
backend/requirements.txt
backend/services/__init__.py
backend/services/github.py
docs/github_integration.md
frontend/src/app/profile/profile-editor/profile-editor.component.css
frontend/src/app/profile/profile-editor/profile-editor.component.html
frontend/src/app/profile/profile-editor/profile-editor.component.ts
frontend/src/app/profile/profile.service.ts

With this commit, users can navigate to the profile page and link/unlink their GitHub account. This stores their username, avatar, and id in the `user` table. Having an avatar will serve many other site features.
Development and feature notes are found in `docs/github_integration.md` Additional environment variables and development app setup at GitHub is needed for this feature to work in development.
This is the first commit to land in production following relaunch, so I am adding migration scripts via alembic. Migration scripts will be needed moving forward to avoid clobbering data in production. Ahead of merging into production, be prepared to carry out the migration with documentation found in `docs/github_integration.md`.
This PR closes #33.

Link GitHub accounts with CSXL accounts

---

Dockerfile

This is a hotfix for the alembic.ini file not being included in the
Dockerfile build process for production.

Add alembic.ini to Dockerfile build

---

backend/api/authentication.py
frontend/src/app/profile/profile.service.ts

The UNC Shiboleth proxy in production is protecting the /auth routes.
It appears this proxy is creating issues with the GitHub OAuth
integration. Instead of prefixing /auth for the return URL, we are now
going to prefix /oauth for OAuth related URLs.

Change OAuth route to avoid UNC SSO Proxy conflict

---

frontend/src/app/organizations/widgets/org-details-info-card/org-details-info-card.widget.html
frontend/src/app/organizations/widgets/org-details-info-card/org-details-info-card.widget.ts
frontend/src/app/organizations/widgets/organization-card/organization-card.widget.css
frontend/src/app/organizations/widgets/organization-card/organization-card.widget.html
frontend/src/app/organizations/widgets/organization-card/organization-card.widget.ts

Fixed the following bug: On the organizations page, sometimes the tooltip would not show because of the way it was hard-coded to the length of characters in the description.
- Added a function that checks whether or not the description height has been clipped, which is a more accurate indication of whether or not the tooltip should be shown
- Removed some unnecessary CSS
Ran `honcho start`, made sure the tooltip showed up for all descriptions with ellipses.
> *This PR resolves issue #56 *

Fix issue with tooltip not showing

---

frontend/src/app/organization/widgets/organization-card/organization-card.widget.css
frontend/src/app/organization/widgets/organization-details-info-card/organization-details-info-card.widget.css
frontend/src/app/organization/widgets/organization-details-info-card/organization-details-info-card.widget.html
frontend/src/app/organization/widgets/organization-details-info-card/organization-details-info-card.widget.ts

This pull request edits the CSS and styling of the organizations and organization details pages.
- Set line height to two times the font size plus a little extra for the space between each line
- Fix the bottom margin of the card so the spacing is consistent with the top part of the card
- Reduce the font size on the Organization Details page and restyle the main card accordingly
- Align the organization logo to the top left of the card
- Response styling on the organization details page (for phones, tablets, laptops, and monitors)
These changes were thoroughly tested on the local server by running `honcho start` and with various screen sizes.
Original Laptop View
Monitor View
Tablet Views (Portrait and Landscape)
Phone Views (Portrait and Landscape)
Please provide feedback on some of the …

Organization Page Styling

---

frontend/src/app/admin/organization/list/admin-organization-list.component.css
frontend/src/app/admin/organization/list/admin-organization-list.component.html
frontend/src/app/admin/organization/list/admin-organization-list.component.ts
frontend/src/app/admin/organization/organization-admin.service.ts
frontend/src/app/organization/organization-editor/organization-editor.component.css
frontend/src/app/organization/organization-editor/organization-editor.component.html
frontend/src/app/organization/organization-editor/organization-editor.component.spec.ts
frontend/src/app/organization/organization-editor/organization-editor.component.ts
frontend/src/app/organization/organization-routing.module.ts
frontend/src/app/organization/organization.module.ts
frontend/src/app/organization/organization.service.ts

This PR updates the frontend to include a tab for "Organizations" on the admin page as well as an organization creation form. These two features allow for the creation, deletion, and viewing of organizations in the database.
- Added relevant TS, HTML, and CSS files for the Organization Admin page.
- Added relevant TS, HTML, and CSS files for the Organization Editor page.
- Modified modules/routing to accommodate for the new components.
These changes were thoroughly tested on the local server by running `honcho start`.
> *This PR resolves issue #52*

Migrate Organization Admin Page

---

backend/entities/organization_entity.py
backend/migrations/versions/f7ad0c30eb78_add_organization_table.py

This PR introduces two changes:
1. More concretely specifies a few of the properties of OrganizationEntity to enforce schema level constraints. Specifically:
- name is not nullable and defaults to empty string
- slug is not nullable and is enforced unique at the schema level
- public is not nullable and defaults to true
2. Adds an alembic upgrade/downgrade script in preparation for production deployment

Update OrganizationEntity and Add alembic migration script for Organization table

---

backend/services/organization.py
backend/test/services/organization/organization_test.py

This PR fixes test that were failing due to the slug refactor. Minor changes were needed here, as well as one leftover issue from a previous PR being merged in.

Organization Test Fix for Refactor

---

frontend/src/app/shared/search-bar/search-bar.widget.html
frontend/src/app/shared/search-bar/search-bar.widget.ts

This PR fixes a bug where the clear button does not reset the list of organizations shown. Made a minor change to add a new function that resets the search bar from the typescript file.

Fix clear functionality

---

frontend/src/app/admin/organization/admin-organization.resolver.ts
frontend/src/app/admin/organization/admin-organization.service.ts
frontend/src/app/admin/organization/list/admin-organization-list.component.html
frontend/src/app/admin/organization/list/admin-organization-list.component.ts
frontend/src/app/organization/organization-details/organization-details.component.ts
frontend/src/app/organization/organization-editor/organization-editor.component.ts
frontend/src/app/organization/organization-filter/organization-filter.pipe.ts
frontend/src/app/organization/organization-page/organization-page.component.html
frontend/src/app/organization/organization-page/organization-page.component.ts
frontend/src/app/organization/organization.resolver.ts
frontend/src/app/organization/organization.service.ts

This PR refactors the Organization Details page to use a route resolver to retrieve the organization and its data rather than subscribing to directly within the component. It also fixes the titleResolver so it uses the organization from the route instead of making its own HTTP request to get the organization name.
- Updated the Organization Service to remove profile retrieval since the profile isn't actually used in that service.
- Added an Organization Resolver TS file to store the `organizationResolver` ResolveFn.
- Refactored the Organization Details Component to use the `organizationResolver` rather than directly calling the service and subscribing to the returned Observable.
- Changed the `title` in the route to be a child of the main route so it can inherit from the Organization …

Improve Organization Retrieval for Organization Details Page

---

backend/services/organization.py

This PR cleans up a couple of organization backend methods.
- Made `get_from_slug` more idiomatic, using `one_or_none()` instead of `[0]`
- Changed organization update method to check for admin permissions instead of org roles
All changes were tested thoroughly on the local server by running `honcho start`. Note: since we don't have the edit organization functionality yet, I wasn't able to fully test whether my admin permission check worked.
Resolves issue #81

Clean Up Organization Backend

---

frontend/src/app/admin/organization/list/admin-organization-list.component.ts

This PR implements a quick fix to ensure that the HTML updates after an organization is deleted on the organization admin page.
- Added a line in the subscription to deleteOrganization() to filter out the organization from the component's organizations array.
All changes were tested on the local server after running `honcho start`.
This is a temporary fix (modeled after how the admin roles list is updated). This will be changed if the code is refactored to use RXJS objects throughout the application.

Fix Organization List HTML Update After Delete

---

frontend/src/app/navigation/navigation.component.html

This PR adds the organizations route to the nav bar when a user is not signed in
- Added organizations route to nav bar when not signed in
- Fixed some spacing discrepancies with mat-divider
- Run honcho start
- Check signed in nav bar and signed out nav bar
- Confirm links still work

Update organizations route

---

frontend/src/app/organization/organization-editor/organization-editor.component.html
frontend/src/app/organization/organization-editor/organization-editor.component.ts
frontend/src/app/organization/organization.resolver.ts
frontend/src/app/organization/organization.service.ts
frontend/src/app/organization/widgets/organization-details-info-card/organization-details-info-card.widget.html
frontend/src/app/organization/widgets/organization-details-info-card/organization-details-info-card.widget.ts

This PR gives admins the ability to update organizations. The edit button is on the details page for each organization and is currently shown if the current user is a website admin (will be changed to organization permissions once we establish the organization to user relationship table).
- Organization editor uses `organizationResolver` to grab the current organization's data
- `organizationResolver` returns an empty organization if the slug is `new`
- Organization editor is connected to the organization details page and can update organizations
- Run honcho start
- If you sign in as an unauthorized user, there should be no edit button the organization details page and trying to go to `organizations/slug/edit` should take you back to the home page
- If you are signed in as an admin, you …

Update Functionality in Organization Editor

---

backend/api/events.py
backend/api/organizations.py
backend/entities/__init__.py
backend/entities/event_entity.py
backend/entities/organization_entity.py
backend/main.py
backend/models/__init__.py
backend/models/event.py
backend/models/event_details.py
backend/models/organization_details.py
backend/script/demo_reset.py
backend/script/test_reset.py
backend/services/event.py
backend/services/organization.py
backend/test/services/event/event_demo_data.py
backend/test/services/event/event_test_data.py
backend/test/services/organization/organization_demo_data.py

This major pull PR provides the implementation of the Python backend for the Events feature. This includes the SQLAlchemy Entities and Pydantic models, backend services, FastAPI routes, and test data. 
- Added the `EventEntity` SQLAlchemy Entity to model how events should be stored in the PostgreSQL database.
- Established a one-to-many relationship between the `organizations` and `events` tables through the SQLAlchemy Entities.
- Added the `Event` and `EventDetail` Pydantic models to represent the shape of events data to be exposed by the APIs. The `EventDetail` model exists to prevent circularity between the `Event` and existing `Organization` Pydantic models.
- Added demo and test data for events. This data should populate when the `demo_reset.py` or `test_reset.py` scripts are run …

Implement the Events Feature Backend

---

frontend/angular.json

This is a hot fix to avoid a limitation of bundle size to unblock deployment.

Fix bundle size limitation in build

---

frontend/src/app/coworking/widgets/dropin-availability-card/dropin-availability-card.widget.ts

We use an epsilon of just under 1 minute to combat the potential for clock drift on devices relative to the server's time. Difficult to reproduce in dev due to server and client sharing the same system clock, but experienced in prod on day 0 with many laptops having slightly drifted system clocks.

Fix clock drift issue on dropin availability card

---

backend/api/admin/roles.py
backend/services/role.py
backend/test/services/role_test.py
frontend/src/app/admin/roles/list/admin-roles-list.component.html
frontend/src/app/admin/roles/list/admin-roles-list.component.ts
frontend/src/app/admin/roles/role-admin.service.ts

Add the ability for administrators to create new roles in the backend User Admin UI.
A new button is added to the Roles Table:
We use system prompt widget to gather the name of the new role. Upon providing a name, the new role is created and the user is redirected to the role editor page.

Add ability to create roles as an Admin

---

frontend/src/app/event/event-filter/event-filter.pipe.ts
frontend/src/app/event/event.model.ts
frontend/src/app/event/event.service.ts

This PR fixes a major bug that prevented the events page from sorting correctly.
- Reimplement date sorting into the `EventFilterPipe`.
- Create the `EventJson` model to represent the exact types of data retrieved from the API.
This was needed because dates from the API are returned as strings and are not implicitly coerced
into the `Date` type.
- Create the `parseEventJson` pipeable function to convert `EventJson` models to `Event` models.

Fix Sorting Bug for Events Page

---

frontend/src/app/event/event.model.ts
frontend/src/app/event/event.service.ts

This PR fixes a critical bug preventing the Organization Detail page from loading.
Specifically, it creates a new resolver for event data to receive that directly from the API rather than through the Organization object.

Fix Organization Detail Page Crash

---

.devcontainer/Dockerfile

The previous installation mechanism was deprecated which caused a minute-long pause in the install unnecessarily. The Dockerfile is now updated to reflect preferred Node Source installation method for Node v18.

Update DevContainer Dockerfile to latest Node dist

---

frontend/src/app/organization/organization-details/organization-details.component.css

This commit adds right padding to the Organization Details Event List to make padding on mobile devices a bit more even.

Add Right Padding to Org Details Event List

---

backend/api/coworking/operating_hours.py
backend/main.py
backend/services/coworking/exceptions.py
backend/services/coworking/operating_hours.py
backend/test/services/coworking/fixtures.py
backend/test/services/coworking/operating_hours_test.py

This PR lands the ability to add and delete Operating Hours from the Coworking feature of the XL.
The following changes are included in this PR:
* OperatingHours specific API endpoints
* New Service Methods for `get_by_id`, `create` and `delete`
* Tests for service methods
Validated by writing unit tests with 100% coverage of the `OperatingHoursService`.

Add and Delete Operating Hours from Coworking Database via API

---

docs/branches.md

This pull request adds a template for PRs to the `branches` docs page.

Add PR Template to the Docs Page

---

docs/admin_permissions.md
docs/auth.md
docs/feature_permissions.md

This PR adds the Feature Permissions Document to the docs directory. This document defines the standard permissions for each feature in the application to serve as a reference when adding permissions to roles, as well for creating new feature permissions.
Descriptions of the feature permissions for the Coworking feature have not been added yet!

Feature Permissions Document

---

frontend/src/app/organization/organization-details/organization-details.component.html
frontend/src/app/organization/organization-details/organization-details.component.ts
frontend/src/app/organization/organization.module.ts
frontend/src/app/organization/organization.resolver.ts
frontend/src/app/organization/widgets/organization-not-found-card/organization-not-found-card.widget.css
frontend/src/app/organization/widgets/organization-not-found-card/organization-not-found-card.widget.html
frontend/src/app/organization/widgets/organization-not-found-card/organization-not-found-card.widget.ts

This PR aims to improve the UX when a user navigates to an invalid organization. 
- Rework the organization resolver to return `undefined` upon an error retrieving an organization, allowing us to handle this scenario in the frontend without immediately causing a crash. This uses RxJS's `pipe`, `catchError`, and `of` functions.
- Add a new widget called `OrganizationNotFoundCard` that shows only when an organization is not found.
- This feature was tested on the frontend using `honcho start`.
*This PR resolves #83*

Improve UX When Navigating to an Invalid Organization

---

frontend/src/app/app-routing.module.ts

The routes for coworking home and ambassador should be contained in the coworking routing module exclusively, not duplicated in app-routing. This commit removes the routes from app-routing.module.ts.

Fix duplication of routes in app and coworking

---

backend/api/static_files.py
backend/main.py

Use the FastAPI GZip middleware to compress responses; especially the static file responses of the application in production, in order to reduce load times and network transfer over cell networks.
This commit also fixes some typing issues in the StaticFiles middleware.
Verified by testing locally and confirming GZip responses coming from the API.

Compress HTTP responses for faster load times

---

frontend/src/app/event/event-page/event-page.component.ts

This PR fixes a bug where the initially selected event would occasionally show a past event rather than the most upcoming event.

Pass Initial Selected Event Through Pipe

---

backend/api/events.py
backend/entities/event_entity.py
backend/entities/event_registration_entity.py
backend/models/event_details.py
backend/models/event_registration.py
backend/services/event.py
backend/test/services/event/event_test.py
backend/test/services/event/event_test_data.py

We need registrations to events to be limited to users with permission to view. This PR is not ready for merge, but is the start of progress on this front.

Protect EventRegistrations attendees from accidental API disclosure

---

backend/database.py
backend/env.py

This commit fixes an issue when working in the REPL with backend code.
The fundamental issue is path related and resolved by using an absolute
path in the `dotenv` loader for our development environment.
A type annotation was also added to backend/database.py to align with
project style.

Use absolute path to .env file in backend/env.py

---

backend/script/repl.py

Developers can now run `python3 -i backend/sscript/repl.py` and be dropped into a development REPL with the most commonly useful classes, as well as some initialized services, loaded into the global namespace.

Add script to simplify backend REPL experiments

---

frontend/src/app/admin/admin.component.html
frontend/src/app/coworking/ambassador-home/ambassador-home.component.css
frontend/src/app/coworking/ambassador-home/ambassador-home.component.html
frontend/src/app/coworking/widgets/coworking-reservation-card/coworking-reservation-card.html

This pull request changes the color of the buttons and tabs on dark mode to white outlines to be consistent with the rest of the application.
- Changed admin tabs from pink to white outlines
- Changed coworking dark mode buttons from pink to white outline buttons
- Changed ambassador dark mode buttons from pink and red to white outline buttons
- Added a right-margin to the ambassador reservation card so that the buttons don't touch
*This PR resolves #159*
Notes:
I kept the `Revoke` and `Grant` permission buttons on Admin page the same colors.

Dark Mode Button and Tab Styling

---

.devcontainer/Dockerfile

Tab autocompletion has created a duplicate letter for some time. This commit applies a fix found on the web: installing the locales aptitude package and establishing the locale as en_US.UTF-8. Verified by trying tab autocompletion in zsh terminal in VSCode and it works!

Fix longstanding autocomplete issue in zsh

---

frontend/src/app/profile/profile-editor/profile-editor.component.css
frontend/src/app/profile/profile-editor/profile-editor.component.html
frontend/src/app/profile/profile-editor/profile-editor.component.ts

This PR gives students the ability to display/copy the bearer token of a user after signing in. It removes the tedious process of having to continuously access the browsers developer tools when wanting to test the backend. I decided to add the feature to the Profiles page, because when signing in that is the page users are led to. 
Potential Improvements:
1.  Getting rid of this weird margin between the buttons and the token itself.

Add Generate Bearer Token feature

---

.devcontainer/Dockerfile

DevContainer Dockerfile now downloads and installs the oc client for OpenShift. This enables a workflow of working with staging/production within the DevContainer terminal and removes a small hurdle for students needing to download and correctly install oc. Even more optimistically this enables us to begin scripting many devops/deployment concerns in the codebase. Some thought will need to be put into guard rails to avoid accidentally scripting against the production site before scripting anything, though!
As this changes the dev Dockerfile, a rebuild of the DevContainer is needed once the commit is pulled into a dev repository.

Add oc OpenShift Client to DevContainer

---

frontend/src/app/navigation/navigation.component.html

This PR makes it to where when a user with admin permissions clicks on User Admin, they will be directed to the Users table rather then the blank page!

User Admin tab should Navigate to Users Table

---

frontend/src/app/coworking/coworking.module.ts
frontend/src/app/coworking/widgets/operating-hours-dialog/operating-hours-dialog.widget.css
frontend/src/app/coworking/widgets/operating-hours-dialog/operating-hours-dialog.widget.html
frontend/src/app/coworking/widgets/operating-hours-dialog/operating-hours-dialog.widget.ts
frontend/src/app/coworking/widgets/operating-hours-panel/operating-hours-panel.widget.css
frontend/src/app/coworking/widgets/operating-hours-panel/operating-hours-panel.widget.html
frontend/src/app/coworking/widgets/operating-hours-panel/operating-hours-panel.widget.ts

This PR implements a new design for the operating hours expansion panel on the coworking page. The new design utilized the Material `outlined` style and fits better into the style of the site. The new design also uses a Material Dialog component to display operating hours.
* We may be able to add some text specifying to the user when the XL will reopen.
* Better logic for when the XL has no future operating hours.

Implement Design for Operating Hours

---

backend/services/event.py

This small PR fixes an issue in the EventService where we use two queries to retrieve events for an organization by a slug. Instead, we have moved towards using the `.join()` syntax that is now standard, making the code more concise and efficient.

Fix Querying Methods in Backend Service Logic

---

backend/api/events.py
backend/api/organizations.py
backend/services/event.py
backend/services/organization.py
backend/test/services/event/event_test.py
backend/test/services/organization/organization_test.py

As noted in the https://github.com/unc-csxl/csxl.unc.edu/pull/196 PR, @KrisJordan recommended that we standardize around the convention of calling getter backend service methods that use parameters get_by_{arg} rather than get_from_{arg}.
This PR makes this change in the backend for organizations and events.

Use get_by Convention in Organizations and Events

---

backend/entities/academics/section_entity.py
backend/models/coworking/__init__.py
backend/models/roster_role.py
backend/services/academics/term.py

1. Added the view only `staff` relationship to `SectionEntity` which places a limit on the join.
2. Reverted my suggested enum changes because after looking in the actual database, SqlAlchemy appears to only store the enum name not the enum value.
3. Fixed some imports in coworkign models that prevented the repl script from loading
4. Slight modification to the current term query to limit the number of rows returned by the database to be 1 in SQL rather than in fetching after SQL executes

Minor changes for the academics feature

---

frontend/src/app/academics/section-offerings/section-offerings.component.ts

This small PR temporarily hides the 'Instructor' column on the Section Offerings view while the admin feature for staff is developed.

Temporarily Hide Instructor Column on Section View

---

backend/script/generate_migration.py
backend/script/reset_demo.py
backend/script/reset_testing.py

This PR has two developer experience (DX) quality of life improvements:
1. Improves upon the reset_demo and reset_test backend scripts by shelling out to run the scripts database_delete and database_create each time a database is reset. This avoids a common issue when developing new schema with foreign key constraints where resetting fails, so developers would need to manually go back and run delete/create database scripts.
2. Adds a script for generating migrations based on a remote branch.

Improved DX scripts:  delete/create database in reset scripts, add migration generation script

---

backend/migrations/README

Some additional steps were added to be sure that the devcontainer's database state is up-to-date with `main`, including, importantly, alembic's migration table.

Improve migration instructions 

---

backend/services/coworking/policy.py
backend/services/coworking/reservation.py
backend/test/services/coworking/reservation/get_map_current_reservations_test.py

This is not a PR to `main` but rather a PR to `room-reservations`. The way Jade and I had decided to move forward with merging strategies for our feature was to send PR into the room reservation branch. Once we have made the necessary changes required to launch the beta version for our feature, we will merge `room-reservations` into main, which will be a giant merge. Was just wondering if you were okay with this strategy @KrisJordan?
Previously, we were just iterating over a hardcoded list to get all the rooms available. This change ensures that we instead query the rooms database to get all the reservable rooms. There is also a test for this method.
However, one thing I did notice is that this query only returned 4 reservable rooms. I am sure that there are more than 4 reservable rooms, …

[Room Reservations] Query DB instead to get list of reservable rooms

---

backend/entities/office_hours/oh_event_entity.py
backend/entities/office_hours/oh_ticket_entity.py

This PR makes changes to our entities that reflect the modifications requested of our Pydantic models.
- Several string fields are now non-nullable, with a default of empty string, if they are optional fields
- `location_id` is changed to `room_id`
- Defaults given for fields with DateTime types

Fix fields in OH entities to match models

---

frontend/src/app/event/event-editor/event-editor.component.html
frontend/src/app/event/event-editor/event-editor.component.ts
frontend/src/app/shared/user-lookup/user-lookup.widget.html
frontend/src/app/shared/user-lookup/user-lookup.widget.ts

The User Lookup widget has a few characteristics that are specific to its initial use in the EventEditorComponent. This PR makes the component more generic and refactors a few minor improvements:
1. Make the control label an input of the control
2. Use a notion of the control being "disabled" rather than have it based on some "adminPermission" which made sense in the context of EventEditorComponent
3. Add an optional `maxSelected` input property which is `null` by default. If set to a number, the control prevents the addition of more users. (My new use case for this widget elsewhere is a select one.)
Since this involved refactoring some of the `event-editor.component.html` file, I made some small improvements there, as well.

Make User Lookup widget more generic

---

backend/api/coworking/reservation.py
backend/models/coworking/__init__.py
backend/models/coworking/availability.py
backend/models/coworking/operating_hours.py
backend/models/coworking/reservation.py
backend/models/coworking/time_range.py
backend/services/coworking/policy.py
backend/services/coworking/reservation.py
backend/test/services/coworking/reservation/get_map_current_reservations_test.py
backend/test/services/coworking/time.py
frontend/src/app/coworking/coworking.models.ts
frontend/src/app/coworking/room-reservation/reservation-table.service.ts
frontend/src/app/coworking/widgets/room-reservation-table/room-reservation-table.widget.ts

closes #264, #288 
This PR addresses the issue of students being able to reserve rooms even when the XL is closed, which served as "false advertising." Now Sally Student should only be able to reserve rooms based on the operating hours of the XL. That is, Sally can only reserve a room on a date when the XL has listed operating hours. Addressing this issue in turn required us to make the table dynamic so that it changes size based on the duration of the operating hours.
- Instead of hardcoding values to only allow reservations from 10 am to 6 pm, we now query the database to retrieve the list of operating hours. This allows our table logic to be more abstract.
- We introduced `ReservedMapDetails` as a pydantic model to facilitate this data transfer to the frontend. 
- We added some helper …

Dynamic Room Reservation Table based on Operating hours

---

backend/services/coworking/policy.py
backend/services/coworking/reservation.py
backend/test/services/coworking/reservation/get_map_current_reservations_test.py

Please review PR #311 before this one, since this builds off of the changes made in that PR.
We need some way to block out the rooms when they are being used for Office Hours. That is, Sally student should not be able to reserve a room during a timeslot when it is being used for office hours.
closes #312 
- This PR addresses this issue by graying out the cells when an office hour might be made.
- The office hours are currently hardcoded in the coworking policy. They should be fairly easy to change, but they would require someone to make changes in the codebase to reflect. I had considered developing a frontend and making a table in the backend to keep track of office hour events. But it looks like the 523 group is already going to be working on this feature. So as a temporary solution to …

Restrict room reservations during office hour timeslots

---

backend/services/exceptions.py
backend/test/services/event/event_test.py
backend/test/services/organization/organization_test.py
backend/test/services/organization/organization_test_data.py

This small PR adds more Pytests to get the tests for `OrganizationService` and `EventService` to 100%.
This PR also removes the unused `OrganizationNotFoundException`, which was causing the exceptions to not hit 100% test coverage.

Get Organization / Event Test Coverage to 100%

---

backend/test/services/academics/section_data.py
backend/test/services/academics/section_test.py

This small PR adds more Pytests to get the tests for `SectionService` in the academics feature to 100% coverage.

Get Academics Test Coverage to 100%

---

frontend/src/app/coworking/widgets/operating-hours-panel/operating-hours-panel.widget.css
frontend/src/app/coworking/widgets/operating-hours-panel/operating-hours-panel.widget.html

This small pull request properly right-aligns the "All Hours" button on the coworking home page. In addition, since this information would be valuable off-hours, the button now also appears when the XL is closed.

Fix Design of Coworking Hours Button

---

frontend/src/app/academics/academics-home/academics-home.component.html
frontend/src/app/academics/section-offerings/section-offerings.component.html

This small PR updates the academics home page card and the section dropdown in the section page to use the Material outlined style.

Fix Academics Home and Section Dropdown to Use Outlined Style

---

backend/services/coworking/policy.py
frontend/src/app/coworking/room-reservation/room-reservation.service.ts
frontend/src/app/coworking/widgets/dropin-availability-card/dropin-availability-card.widget.ts

There has been a rarely encountered, but long-standing bug in the front-end of the drop-in UI. The bug was when a group of seats was not reservable except for in the future, we would advertise "reservable in X minutes" but clicking the button would lead to an error (bad reservation request) if the time period was beyond the pre-reservation time window (previously 30 minutes ahead, dropping down to 10 for now).
With the move to room reservations, this bug becomes more common because we are still showing the drop-in seat selection widget when the XL is closed. Pulling the site up ahead of opening, shows a view like this (shown after clicking one of the options): 
This PR prevents the drop-in widget from advertising seats as reservable in the future when outside of the pre-reservation window …

Hot-fix for bug in front-end with desk drop-in prereservations

---

backend/api/office_hours/oh_ticket.py
backend/services/office_hours/oh_ticket.py

Add OH ticket API endpoints with new models
- create, update (for students editing), update state, get by section id, get by section id and user, get by event
Add Service files skeleton — func defs + starter thoughts
- all function bodies are WIP/TODO
- changed `update` ticket API route to take in non-draft model, so that the service can use an id from the db
- OHTicketService: create, get tickets by section, get tickets by section and user, get tickets by event, update, & update state

303 add ticket api and service skeleton

---

backend/api/office_hours/oh_event.py
backend/api/office_hours/oh_section.py
backend/api/office_hours/oh_ticket.py
backend/services/office_hours/oh_event.py
backend/services/office_hours/oh_section.py
backend/services/office_hours/oh_ticket.py

Add OH section API endpoints with new models:
- Created api routes for OfficeHoursSections (get, create, update, delete)
Add OH event API endpoints with new models:
- Created api routes for OfficeHoursEvents
- get by section id, get upcoming events by section id, get upcoming events by user, create, update, delete
- added fix User subject to api/office_hours/oh_section.py
Add Service files skeleton — func defs + starter thoughts
- all function bodies are WIP/TODO
- changed `update` section & event API routes to take in non-draft model, so that the service can use an id from the db
- OHSectionService: create, delete, get sections by term, get user sections by term, update
- OHEventService: create, update, delete, get events by section, get upcoming events by section, get upcoming events …

Added api routes for events + services, Added skeleton service code

---

backend/services/coworking/reservation.py
backend/test/services/coworking/reservation/get_map_current_reservations_test.py
frontend/src/app/coworking/room-reservation/reservation-table.service.ts

This PR closes #340 and makes some progress towards #341 
-  Round down to the nearest half hour instead of rounding up to the nearest half hour when deleting past timeslots.
- Time slots should be grayed out during the time when a person has a drop-in reservation to the XL.
- Addressed the issue with room reservations table starting at 10:30 am rather than 10:00 am. This was a small edge case that I had missed while implementing the `round_to_closest_half_hour()` helper function, i.e. when minute is exactly 0. 
- We are no longer graying out past timeslots anymore and instead just choose to not display them anymore. This was easy to change since the table is now dynamic and no longer static.

Refactor logic for graying out timeslots

---

backend/services/coworking/policy.py

We need to block off hours to avoid reservations while furniture is getting installed this coming week; this will be reverted and more finite hours will be added later.

Add special hour blocks for furniture install

---

backend/services/coworking/reservation.py
backend/services/organization.py
backend/test/services/coworking/reservation/draft_test.py
backend/test/services/coworking/reservation/reservation_data.py
backend/test/services/coworking/reservation/seat_availability_test.py
backend/test/services/coworking/time.py

This commit fixes a bug in the backend that permits conflicting room reservations to be made. To avoid the conflict, we check to see if any other existing reservations exist for the room in the given time range. If so, we reject by raising an error. This should generally never arise as the front-end prevents room reservations, however we need to enforce it in the backend, too. Tests are added to correct this.
Some tests were noticed to be broken due to small hotfixes made for production and drop-in reservation limits changed. Additionally, a warning in tests from organization tests was fixed. All tests are passing without warning now.
Finally, this commit makes some minor linting fixes (via `black` formatter).

Fix conflicting room reservations bug

---

frontend/src/app/coworking/room-reservation/room-reservation.service.ts

Due to some changes that merged with room reservations, when creating a drop-in reservation and navigating back (intentionally or not) to home you would not see the draft reservation anymore because it was filtered from the home page. This meant a draft reservation was created but could not be cancelled by user or ambassador. This PR fixes this issue by making the draft of a drop-in visible on the home page. No changes in behavior for room reservations.

Fix front-end issue with draft drop-in reservation

---

frontend/src/app/app-routing.module.ts
frontend/src/app/app.module.ts
frontend/src/app/profile/profile-editor/profile-editor.component.html
frontend/src/app/profile/profile-editor/profile-editor.component.ts
frontend/src/app/profile/profile-page/profile-page.component.css
frontend/src/app/profile/profile-page/profile-page.component.html
frontend/src/app/profile/profile-page/profile-page.component.ts
frontend/src/app/profile/profile-routing.module.ts
frontend/src/app/profile/profile.module.ts
frontend/src/app/shared/profile-about-card/profile-about-card.widget.css
frontend/src/app/shared/profile-about-card/profile-about-card.widget.html
frontend/src/app/shared/profile-about-card/profile-about-card.widget.ts

This PR provides implementation for a dedicated Profile Page for CSXL users instead of the current Profile Editor. Moved from the old `profile-page` branch due to merge conflicts.
- Created a profile module to contain the new Profile Page and Profile Editor.
- Created a new Profile Page component and associated HTML and CSS files, which includes a button route to the Profile Editor.
- Created a new User Profile Card widget to display a users name, profile picture, email, and pronouns.
- Moved Github Link and Bearer Token to Profile Page and made minor changes to the styling.
- Created a "Profile Actions" card for github link, community agreement, and auth bearer token.
- Want to add a list of user events to the profile page, but would rather get this merged in first as the user event …

Profile Page Improvements

---

backend/services/coworking/reservation.py

This PR updates the filtering criteria on the backend for getting all reservations for the **AMBASSADOR VIEW** (apologies for the branch name, there was a small misunderstanding). Active reservations used to disappear from the Active section after a certain duration. Now all active reservations show up for their full duration and only disappear until the end time is reached or the student checks out/ is checked out.
Yuvraj has also made the following changes:
Fixed the table to show booked out slots when the start time slot has been dynamically purged from the table. This prevents conflicting reservations.
There was a bug where past reservations would have a start time outside the table due to the table being dynamic. This caused the reservation to not show up at all and let people double …

374 active reservations Ambassador View

---

backend/services/coworking/reservation.py
backend/test/services/coworking/reservation/get_map_current_reservations_test.py

The current problem with the code is that at 11 pm, we were not able to see future reservations in red for tomorrow. This was actually a red herring that led me to look at parts of the code that were not responsible for this.
Then suddenly at 12 am, everything started working as intended. This was the biggest hint for me in debugging this.
Basically on line 345, I just had to add in a condition to check that the date I am getting as a param is the same date as today. Only in that case, should I execute the logic of
end_idx < current_time_idx. However, earlier this was being executed for all reservations which is why whenever we had any reservations which had an end time of less than 11 pm (which most reservations do), our function would just skip over them. This also aligns with what we …

Fix bug with end_idx logic for future reservations

---

Dockerfile

This PR includes changes to the deployment Dockerfile to use yarn in place of npm during the build stage. This should fix the issue with the old `npm install` command maxing the RAM out and breaking the build.
Closes issue #392

Change Dockerfile to use yarn instead of npm

---

frontend/src/app/coworking/widgets/coworking-reservation-card/coworking-reservation-card.html
frontend/src/app/coworking/widgets/coworking-reservation-card/coworking-reservation-card.ts

Closes #399 
This is a short PR that will add back the checkin times for confirmed reservations. 
There was also an addition to the "checkinDeadline" method within coworking-card.ts where it makes the checkin deadline deadline the minimum of the start time + 10 and the end of the reservation so the deadline wouldn't display past the reservation's end time.

399 add checkin time to avoid cancellation verbiage

---

frontend/src/app/coworking/coworking.module.ts
frontend/src/app/coworking/widgets/operating-hours-panel/operating-hours-panel.widget.css
frontend/src/app/coworking/widgets/operating-hours-panel/operating-hours-panel.widget.html
frontend/src/app/coworking/widgets/operating-hours-panel/operating-hours-panel.widget.ts

This pulls request adds reopening time to the Operating Hours Panel in the Coworking page, as well as makes the OH panel responsive on mobile devices. Now, when on mobile, the OH panel becomes a column flex view with proper alignment, rather than a horizontal row flex view.

Add Reopening Time to OH Panel, Make OH Panel Responsive

---

backend/test/services/academics/course_data.py
backend/test/services/academics/section_data.py
backend/test/services/academics/section_test.py

Somewhere along the way in one of the recent PRs, the academics tests broke. This PR fixes this by reversing some of the changes done to the academics test data! All tests now pass.
*This PR closes #435*

Fix Broken Academic Tests

---

backend/api/academics/section_member.py
backend/services/academics/section_member.py
backend/services/office_hours/section.py
backend/test/services/academics/section_test.py
backend/test/services/office_hours/fixtures.py
backend/test/services/office_hours/section/create_test.py

This PR allows the root user to create office hour sections so that there is an API endpoint to add an instructor to the OH section.

Allow root to create OH Sections

---

backend/api/coworking/reservation.py
docs/specs/room-reservation.md
frontend/src/app/coworking/coworking-home/coworking-home.component.html
frontend/src/app/coworking/coworking-home/coworking-home.component.ts
frontend/src/app/coworking/coworking.service.ts
frontend/src/app/coworking/reservation/reservation.service.ts
frontend/src/app/coworking/room-reservation/confirm-reservation/confirm-reservation.component.ts
frontend/src/app/coworking/room-reservation/new-reservation-page/new-reservation-page.component.ts
frontend/src/app/coworking/room-reservation/room-reservation.service.ts
frontend/src/app/coworking/rx-coworking-status.ts
frontend/src/app/coworking/widgets/coworking-reservation-card/coworking-reservation-card.ts

closes #357 
All polling will now take place with the RxObject 'RxCoworkingStatus' to avoid duplicate pulling. 
I also went outside the scope of this branch to refactor how the Room Reservation Service was being utilized and removed duplicate Reservation State Change Methods (like cancel Reservation etc) from this child class in effort to utilize the Reservation Service parent class.
Note:
THe original issue: https://github.com/unc-csxl/csxl.unc.edu/issues/357 mentions 'if there is something missing from the status API endpoint, such as the bound of future reservations is too short (worth checking) then we can fix that.'. I was not sure what this was referring to or how to test if this was an issue. Let me know if this is still worth looking into!

357 avoid duplication of polling data in coworking home

---

frontend/src/app/admin/users/list/admin-users-list.component.ts
frontend/src/app/admin/users/user-admin.service.ts
frontend/src/app/event/event-page/event-page.component.ts
frontend/src/app/event/event.service.ts
frontend/src/app/event/widgets/event-users-list/event-users-list.widget.ts
frontend/src/app/pagination.ts

This pull request creates a new frontend abstraction for pagination. The abstraction supports simple pagination, as well as pagination where the HTTP response model does not match the type of model stored in each page. The abstraction makes strong use of generic types so that the feature is flexible to be used across the site with minimal localization.
This pull request does not implement the abstraction in any features. I was planning on utilizing this in the events feature refactor.
*Again, I am adding @jadekeegan and @atoneyd to this PR, since we have all been working on pagination for quite a while. No need to complete CRs here! You all should not be bothered with notifications after this PR and the events refactor PR come in!*
This PR adds the `Paginator<T, Params>` class, which is …

Create Frontend Pagination Abstraction

---

backend/entities/academics/section_entity.py
backend/models/academics/section_details.py

This pull request removes the `preferred_applicants` field from the backend section model. This field leaks users' application data via the public GET section data API. In addition, this data caused pages relying on sections data to load extremely slowly.
After further analysis, it does not appear that this extra field had any functionality in the backend, so I think it can be safely removed.

Fix Critical Issue - Applications Data Leaking with Section Data

---

backend/entities/academics/section_entity.py
backend/entities/academics/section_member_entity.py
backend/migrations/versions/87dd1109e7b2_migration_for_academics_indexes.py

By adding Indexes to Academics' SectionMemberEntity (by user and by section), and SectionEntity (by term and by course), we should see an automatic performance increase for some common queries (e.g. look up all members of a section or all sections for a user).
This PR also drops the `application_id` column from `SectionMemberEntity` as a cleanup while we're running a migration on the table. When the time comes, this information (linking a section member to their TA application) can be held in a different entity, for example a `TAAssignmentEntity` which can join an application to a member (with additional information such as hiring level, and so on).
Migration created and validated per the `backend/migrations/README` validation steps.

Index Academics join table columns that back common queries

---

backend/migrations/versions/aa567132afd4_complete_my_courses_migration.py

Accidentally missed a dropped column (`office_hours.date`) in the migration for My Courses.

Hotfix for missed dropped field in office_hours table

---

backend/api/academics/section.py
backend/api/academics/term.py
backend/entities/academics/section_entity.py
backend/entities/academics/section_member_entity.py
backend/entities/user_entity.py
backend/models/academics/__init__.py
backend/models/academics/section.py
backend/models/academics/section_member.py
backend/services/academics/section.py
backend/services/academics/term.py
backend/test/services/academics/section_data.py
backend/test/services/academics/section_test.py
backend/test/services/academics/term_test.py
frontend/src/app/academics/academics-admin/course/course-editor/course-editor.component.css
frontend/src/app/academics/academics-admin/course/course-editor/course-editor.component.html
frontend/src/app/academics/academics-admin/room/room-editor/room-editor.component.css
frontend/src/app/academics/academics-admin/room/room-editor/room-editor.component.html
frontend/src/app/academics/academics-admin/section/admin-section.component.html
frontend/src/app/academics/academics-admin/section/admin-section.component.ts
frontend/src/app/academics/academics-admin/section/section-editor/section-editor.component.css
frontend/src/app/academics/academics-admin/section/section-editor/section-editor.component.html
frontend/src/app/academics/academics-admin/section/section-editor/section-editor.component.ts
frontend/src/app/academics/academics-admin/term/term-editor/term-editor.component.css
frontend/src/app/academics/academics-admin/term/term-editor/term-editor.component.html
frontend/src/app/academics/academics.models.ts
frontend/src/app/academics/academics.module.ts
frontend/src/app/academics/academics.service.ts
frontend/src/app/my-courses/catalog/section-offerings/section-offerings.component.css
frontend/src/app/my-courses/catalog/section-offerings/section-offerings.component.html
frontend/src/app/my-courses/catalog/section-offerings/section-offerings.component.ts

This PR adds the ability to set section instructors in the Section Admin form UI.
This PR also reverts the UI changes made in #402 to the academics editors so they are now properly formatted. The admin for this will likely change, but for now, I made some slight M3 styling improvements (including using mat switches and the mat pane widget).

Section Instructor UI, Section Catalog Load Time, and Other Academics Editor Fixes

---

backend/api/hiring.py
backend/entities/__init__.py
backend/entities/application_entity.py
backend/entities/application_review_entity.py
backend/entities/office_hours/course_site_entity.py
backend/main.py
backend/models/application_review.py
backend/script/reset_demo.py
backend/services/__init__.py
backend/services/hiring.py
backend/test/services/fixtures.py
backend/test/services/hiring/hiring_data.py
backend/test/services/hiring/hiring_test.py

This incremental pull request implements the backend for the hiring feature, which allows instructors on course sites to view applicants and change their preference.
* Added the `ApplicationReviewEntity` which connects course sites and applications.
* Create many overview-style models to return only required data to the frontend.
* Created the `HiringService` with the following functionality:
* **Get hiring status:** Retrieves the hiring status that will be displayed on the hiring frontend, separating applications into three columns (see the `HiringStatus` model). This will pair very nicely with Angular's built-in drag-and-drop system. If an application is not associated with an `ApplicationReview` when this method is called, a blank review will be created and persisted in the database.
* …

Implement Backend for Hiring Feature

---

backend/entities/academics/hiring/application_review_entity.py
backend/entities/application_entity.py
backend/models/academics/hiring/application_review.py
backend/services/academics/hiring.py
backend/test/services/academics/course_site_test.py
backend/test/services/academics/hiring/hiring_data.py
backend/test/services/academics/hiring/hiring_test.py
backend/test/services/fixtures.py
backend/test/services/office_hours/office_hours_data.py
frontend/src/app/hiring/dialogs/application-dialog/application-dialog.dialog.css
frontend/src/app/hiring/dialogs/application-dialog/application-dialog.dialog.html
frontend/src/app/hiring/hiring.models.ts
frontend/src/app/hiring/widgets/application-card/application-card.widget.css
frontend/src/app/hiring/widgets/application-card/application-card.widget.html
frontend/src/styles/styles.scss

This pull request adds applicant's course preferences on the the hiring page so that instructors know how each applicant ranks their course.
This PR also fixes a bug which prevented applicants from showing up on other course sites once one course site has been loaded.

Show Applicant Course Preferences on Hiring Page

---

frontend/src/app/hiring/hiring-page/hiring-page.component.css
frontend/src/app/hiring/hiring-page/hiring-page.component.html
frontend/src/app/hiring/hiring-page/hiring-page.component.ts
frontend/src/styles/styles.scss

This PR adds a button to the hiring page that passes on applicants preferring other courses. The button has been thoughtfully designed to include an ***elegant*** and ***expressive*** icon that conveys the button's purpose to the user.
This button will be used as a case study to showcase best design practices in COMP 423 in the fall and all that Material has to offer, and how the smallest of changes to a UI can have the largest of impact.

Add Button to Pass on Applicants Preferring Other Courses 

---

frontend/src/app/organization/organization-editor/organization-editor.component.ts

This small PR fixes the broken organization creation form. Previously, the form checked the organization object's slug to determine if the object was new or not. Now, it correctly checks if the route includes `new` as intended.

Fix the Organization Creation Form

---

backend/api/academics/my_courses.py
backend/models/academics/my_courses.py
backend/models/office_hours/course_site.py
backend/services/academics/course_site.py
backend/test/services/academics/course_site_test.py
backend/test/services/office_hours/office_hours_data.py
frontend/src/app/my-courses/course/course.component.html
frontend/src/app/my-courses/course/course.component.ts
frontend/src/app/my-courses/course/settings/settings.component.css
frontend/src/app/my-courses/course/settings/settings.component.html
frontend/src/app/my-courses/course/settings/settings.component.ts
frontend/src/app/my-courses/my-courses.guard.ts
frontend/src/app/my-courses/my-courses.model.ts
frontend/src/app/my-courses/my-courses.service.ts

This pull request completes the settings page for instructors on the My Courses page. Instructors are now able to add / remove sections, as well as add or remove GTAs and UTAs. Adding a UTA will give them access to the course site. If a user is an existing UTA or GTA, their role will be upgraded.
The settings page is not accessible or visible for students or UTA/GTAs.

Add Settings Page to My Courses, Enable UTA and GTA Selections

---

backend/entities/application_entity.py
backend/models/academics/hiring/application_review.py
backend/models/application.py
backend/services/academics/hiring.py
backend/test/services/academics/hiring/fixtures.py
backend/test/services/academics/hiring/hiring_test.py

This commit refactors the implementation of `HiringService#get_status` to avoid the out of memory errors we are seeing in production with large course sites like COMP110.
The strategy for improving the efficiency is to only execute highly specific SQL queries and manage some of the data joining for the final model building on our end. Hopefully this is a significant improvement! All original tests pass.
This commit also enables administrators to use the API endpoints rather than just course instructors.

Improve resource efficiency of HiringService#get_status

---

frontend/src/app/applications/applications.model.ts
frontend/src/app/applications/form/application-form.component.ts

This small PR ensures that the selected sections on an application form are populated when editing an application.

Fix Course Preferences Not Displaying on Frontend Application After Edit

---

backend/models/academics/hiring/hiring_assignment.py
backend/services/academics/hiring.py
frontend/src/app/hiring/widgets/course-hiring-card/course-hiring-card.widget.html

This hot fix aims to fix an out of memory (crashing) bug seen in production. This is not the full fix, but a temporary workaround. The full fix will need to fetch individual course details in a separate request.

Remove hiring details from overview page

---

backend/services/academics/section_member.py
backend/test/services/academics/section_data.py
backend/test/services/academics/section_member_test.py

This pull request fixes issues with importing students from a CSV into a course roster after the initial upload. It also adds the ability to remove students from the roster if students are not found on a subsequent CSV import, accounting for students who drop the class.

Ensure Students Get Removed from Roster if Not in CSV Import

---

frontend/src/app/my-courses/course/office-hours/office-hours-editor/office-hours-editor.component.html
frontend/src/app/my-courses/course/office-hours/office-hours-get-help/office-hours-get-help.component.html
frontend/src/app/my-courses/course/office-hours/office-hours-get-help/office-hours-get-help.component.ts
frontend/src/app/my-courses/course/office-hours/office-hours-page/office-hours-page.component.html
frontend/src/app/my-courses/course/office-hours/office-hours-page/office-hours-page.component.ts
frontend/src/app/my-courses/course/office-hours/widgets/called-ticket-card/called-ticket-card.widget.css
frontend/src/app/my-courses/course/office-hours/widgets/called-ticket-card/called-ticket-card.widget.html
frontend/src/app/my-courses/course/office-hours/widgets/queued-ticket-card/queued-ticket-card.widget.css
frontend/src/app/my-courses/course/office-hours/widgets/queued-ticket-card/queued-ticket-card.widget.html
frontend/src/app/my-courses/course/roster/roster.component.html
frontend/src/app/my-courses/course/roster/roster.component.ts
frontend/src/app/my-courses/my-courses.model.ts
frontend/src/app/my-courses/my-courses.service.ts
frontend/src/app/my-courses/widgets/course-card/course-card.widget.html

This pull request cleans up the office hours feature for pilot use by both TAs and students.
* Hide the actions columns in office hours events for students so they do not see dummy "edit" and "delete" icons. Also, hide the "Import from Canvas" button on the roster, which was viewable by students (but did not function).
* Hide the currently unused office hours data tab from view.
* Hide PIDs and emails of other students on the roster from the student view. Instructors can still access this data.
* Added labels on the date-time fields on the office hours form.
* Fixed many issues with the office hours description texts. Now, they are properly formatted and work as expected.
* Made some improvements to styling throughout.

Office Hours Feature Fixes

---

backend/models/academics/my_courses.py
backend/services/office_hours/office_hours.py
backend/services/office_hours/ticket.py
backend/test/services/office_hours/ticket_test.py
frontend/src/app/my-courses/course/office-hours/office-hours-get-help/office-hours-get-help.component.css
frontend/src/app/my-courses/course/office-hours/office-hours-get-help/office-hours-get-help.component.html
frontend/src/app/my-courses/course/office-hours/widgets/called-ticket-card/called-ticket-card.widget.css
frontend/src/app/my-courses/course/office-hours/widgets/called-ticket-card/called-ticket-card.widget.html
frontend/src/app/my-courses/my-courses.model.ts
frontend/src/app/shared/user-chip-list/user-chip-list.widget.html

This small PR adds profile images on the office hour ticket cards so that students can have a visual aid to find their TA, and TAs can have a visual aid to find their students.
In addition, the room location and location description now show for students whose tickets have been called.

Add Profile Images and Location Descriptions to Office Hour Tickets

---

frontend/src/app/event/event-editor/event-editor.component.ts

This small pull request fixes the capacity issue for external registrations, where creating an external registration set the event's capacity to 0, causing the frontend to say the event was filled.

Fix External Registration Capacity Issue

---

backend/models/academics/my_courses.py
backend/services/office_hours/office_hours.py
frontend/src/app/my-courses/course/office-hours/office-hours-queue/office-hours-queue.component.css
frontend/src/app/my-courses/course/office-hours/office-hours-queue/office-hours-queue.component.html
frontend/src/app/my-courses/course/office-hours/widgets/called-ticket-card/called-ticket-card.widget.html
frontend/src/app/my-courses/course/office-hours/widgets/queued-ticket-card/queued-ticket-card.widget.html
frontend/src/app/my-courses/my-courses.model.ts
frontend/src/app/my-courses/my-courses.module.ts

This pull request redesigns the office hour queue for TAs. The new page is full-width and displays TA facts and office hour event history. This page is also responsive, showing the queue first, then the facts below.
This PR also fixes the bug found by Will and Chloe relating to `[Object object]` showing up on called tickets.

Office Hours Queue Redesign and Bug Fixes

---

backend/database.py

This PR disables query logging in production. Thanks to new use cases, were overflowing ITS CloudApps logs :)
Verified by changing the `env` variable `MODE` to `production` and seeing logs stop, `development` and logs returned.

Disable SQL Query logging in production

---

backend/models/coworking/reservation.py
backend/services/coworking/reservation.py
frontend/src/app/coworking/coworking.models.ts
frontend/src/app/coworking/widgets/room-reservation-table/room-reservation-table.widget.css
frontend/src/app/coworking/widgets/room-reservation-table/room-reservation-table.widget.html
frontend/src/app/coworking/widgets/room-reservation-table/room-reservation-table.widget.ts

- Added the ability to view the capacity and room type when making a room reservation. Currently, rooms are categorized as "Pairing Rooms" (capacity = 2), "Small Group" (2 < capacity < 6), and "Large Group" (capacity > 6). 
- The formatting of the capacity and room type on the room reservation table can be changed in the future to better meet design requirements. 
**Screenshot:**

Show Room Capacity and Type on the Room Reservation Page

---

frontend/src/app/coworking/room-reservation/new-reservation-page/new-reservation-page.component.html
frontend/src/app/coworking/room-reservation/reservation-table.service.ts

In this PR, I switch the red shade from the default 'red' color to the M3 error40 shade (hex code: #B3261E) for the Room Reservation Table.
The above image depicts the new shade of red implemented in this PR for both the legend and the cells in the room reservation cell property map.

Change 'red' color to match M3 styling

---

backend/services/academics/section_member.py
backend/test/services/academics/section_data.py
backend/test/services/academics/section_member_test.py

This small PR adds an extra check to filter out empty rows in canvas import CSVs as recommended in #624.
*Resolves #624*

Fix Roster Import from Canvas after Grades Added

---

backend/api/static_files.py
backend/main.py

This commit extends the static files middleware so that browsers will not cache the HTML of the SPA. This helps ensure that when new versions are deployed, clients will always get the latest version rather than the cached version. Cached versions tended to be buggy because bundle names of JS files are autogenerated based on hashes of contents.

Do not cache SPA HTML pages in client

---

backend/api/signage.py
backend/entities/office_hours/office_hours_entity.py
backend/main.py
backend/models/__init__.py
backend/models/office_hours/__init__.py
backend/models/signage.py
backend/services/__init__.py
backend/services/academics/course_site.py
backend/services/signage.py
backend/test/services/coworking/reservation/reservation_data.py
backend/test/services/fixtures.py
backend/test/services/room_test.py
backend/test/services/signage_data.py
backend/test/services/signage_test.py
frontend/src/app/tv/tv.service.ts

Two routes were created, `GET /api/signage/slow` and `GET /api/signage/fast`, to provide information to the frontend for the CSXL signage system in an  efficient way. These routes separate the data by update frequency—information that needs quick updates and data that can be refreshed every hour or so. Tests for these routes were added in `backend/tests/services/signage.py`.
The slow route provides the five most recent news items, the next five upcoming events, the top ten users with the most check-ins (including room and CSXL check-ins) for the current month (resetting on the 1st), and the three latest announcement titles. These quantities can be adjusted in the signage service file.
The fast route provides all currently active office hours using the `OfficeHoursOverview` model. This …

[Intermediate] Signage API

---

backend/services/office_hours/office_hours.py

This small pull request fixes the queue sort order to ensure that it is sorted by the ticket's creation time.
*Resolves #639*

Fix Queue Sort Order

---

frontend/src/app/navigation/navigation.component.css
frontend/src/app/navigation/navigation.component.html

Replaces the "login" icon with "account_circle" on all devices, and hides the icon on mobile/thin screens (width < 768px). Also includes multiple toolbar changes to account for the width. Resolves #623.
I felt the "login" icon felt too ambiguous, so I replaced it with "account_circle". Icons like this are seen in other sites and apps as a placeholder for a profile picture when there is none (this site does that as well).
On mobile, only the icon was displayed. However, I felt that an icon by itself did not convey enough--so to completely eliminate ambiguity, the chip reads "Sign In", without the icon, when the user is signed out.
This probably shouldn't cause overflow except on significantly older or smaller devices. To account for this, I modified the toolbar:
- The left side of the …

Replace login icon, show "Sign In" text on mobile over icon

---

frontend/src/app/hiring/hiring-preferences/hiring-preferences.component.css
frontend/src/app/hiring/hiring-preferences/hiring-preferences.component.html
frontend/src/app/hiring/hiring-preferences/hiring-preferences.component.ts

This PR adds error messages when instructors attempt to select TA preferences but the API request fails. This is most often encountered when request payloads are intercepted by UNC's campus firewall and a 403 error is emitted. A custom error message gives the instructor an indication that the requests failed due to not being on a campus network or VPN.
Additionally, drag and drop is disabled while preferences are being arranged. This is necessary for high demand courses where preference persistence is expensive and avoids race conditions when sorting preferences goes faster than the backend keeps up with.
This PR was verified locally by editing the API endpoint to present 403 errors and emulate long requests. Those changes were not committed.

Improve Exception UX in Instructor Hiring Preferences

---

backend/services/user.py
backend/test/services/user_test.py

Previously, search results for users were limited to 10 and you could not search for the combination of first and last name. This PR fixes it. Validated with an additional unit test.

Allow searching for users by first and last name

---

backend/services/user.py

This commit further improves user search as number of users in the system grows.
First, it prioritizes start of string matches (e.g. "Ia" matches "Ian" but not "Christian") in first pass. Only matches middle of strings if no prefix matches are found.
Second, it orders results by first name then last name for a much better UX of disambiguating matches as the number of users in our system has grown significantly.

Search users by prefix matches and order results by first, last name

---

frontend/src/app/my-courses/course/roster/roster.component.ts
frontend/src/app/my-courses/dialogs/import-roster/import-roster.dialog.html
frontend/src/app/my-courses/dialogs/import-roster/import-roster.dialog.ts

This small PR adds clarity to import roster instructions and ensure that the error message is displayed on the dialog (rather than the inconspicuous `[object Object]`.

Roster Import Description Patch

---

frontend/src/app/my-courses/course/office-hours/office-hours-queue/office-hours-queue.component.css
frontend/src/app/my-courses/course/office-hours/office-hours-queue/office-hours-queue.component.html

We are removing historical stats from the more frequent query pulling office hours queue as large courses have began using the system. We will restore this functionality soon!

Temporarily remove Office Hours sidebar

---

frontend/src/app/signage/signage.component.html
frontend/src/app/signage/signage.component.ts
frontend/src/app/signage/signage.model.ts
frontend/src/app/signage/signage.service.ts
frontend/src/app/signage/widgets/event-card/event-card.widget.ts
frontend/src/app/signage/widgets/leaderboard/leaderboard.widget.ts
frontend/src/app/signage/widgets/news-card/news-card.widget.ts

This intermediate signage PR changes the weather to use the CSXL conventions of signals instead of observables. This also reduced some complexity on the signage component level. This ended up revealing some race conditions on the `ngOnChanges` method of the slow data. The fix was found through deepseek and was simply setting the index to 0 on the change. Unfortunately this does mean that every 20 or so minutes when the slow data loads, all the slow widgets will reset off time with the spinners.

Signage fix weather errors

---

backend/api/office_hours/office_hours.py
backend/entities/office_hours/office_hours_entity.py
backend/models/office_hours/office_hours.py
backend/models/office_hours/office_hours_details.py
backend/services/office_hours/office_hours.py
backend/services/office_hours/office_hours_recurrence.py
backend/test/services/office_hours/office_hours_data.py
backend/test/services/office_hours/office_hours_recurrence_test.py
backend/test/services/office_hours/office_hours_test.py
frontend/src/app/my-courses/course/office-hours/office-hours-editor/office-hours-editor.component.css
frontend/src/app/my-courses/course/office-hours/office-hours-editor/office-hours-editor.component.html
frontend/src/app/my-courses/course/office-hours/office-hours-editor/office-hours-editor.component.ts
frontend/src/app/my-courses/course/office-hours/office-hours.resolver.ts
frontend/src/app/my-courses/my-courses.model.ts
frontend/src/app/my-courses/my-courses.module.ts
frontend/src/app/my-courses/my-courses.service.ts

This PR implements functionality on the backend and the frontend to update recurring events such that users have the option to update one single event OR update the chosen event and all future events.
1. Create a term and course section through the Academics Admin page.
2. Create a course site for the course section created.
3. Create a new recurring event.
4. Click the editor for one of the events. Pay attention to which one you choose to ensure that only that event and ones after it are modified!
5. Check the box for updating future events to access the recurrence pattern options.
6. Change the recurrence pattern.
7. Ensure everything works as expected.
8. Complete steps 4-7 for a non-recurring event.

Task/CSXL-653: Update Recurring Events

---

Caddyfile
backend/api/websocket.py
backend/main.py
frontend/src/app/about/about.component.ts

Extracting (and slightly refactoring) WebSocket example from your larger PR to be sure connections still work through the ONYEN login proxy we sit behind. Going to deploy this now.
If this works, I believe the primary change needed in #634 is going to be extracting WebSocket concerns out of the StaticFilesMiddleware.
Additionally, we can base `ws`/`wss` on the protocol of the window's location so that we have working connections in both prod and dev.

Add simple proof of concept WebSocket test for production purposes

---

frontend/src/app/my-courses/course/course.component.ts
frontend/src/app/my-courses/course/statistics/statistics.component.css
frontend/src/app/my-courses/course/statistics/statistics.component.html
frontend/src/app/my-courses/course/statistics/statistics.component.ts
frontend/src/app/my-courses/my-courses-routing.module.ts
frontend/src/app/my-courses/my-courses.module.ts
frontend/src/app/my-courses/my-courses.service.ts
frontend/src/app/shared/mat/filter-chip/dialog/filter-chip-dialog.component.css
frontend/src/app/shared/mat/filter-chip/dialog/filter-chip-dialog.component.html
frontend/src/app/shared/mat/filter-chip/dialog/filter-chip-dialog.component.ts
frontend/src/app/shared/mat/filter-chip/filter-chip.component.css
frontend/src/app/shared/mat/filter-chip/filter-chip.component.html
frontend/src/app/shared/mat/filter-chip/filter-chip.component.ts
frontend/src/app/shared/shared.module.ts
frontend/src/styles/styles.scss

This PR creates a custom, reusable dropdown filter chip component that can be used across the UI when designing filterable interfaces.
The regular filter chip shows placeholder text and an icon, which are both configurable.
Clicking on the chip displays a filterable multi-selection list, allowing for multiple inputs to be selected at once. The first selected item is shown on the chip. If more than one item are selected, the number of items selected in addition to the one shown is displayed. This follows Material conventions, and a chip like this can be found on the official Google Drive app:
There is also a button to easily clear the filterable selection.
The new filter chip item has been placed in the `SharedModule` and therefore can be used throughout the site. It has certain required …

(task:713) Implement Material Dropdown Filter Chip

---

backend/api/academics/my_courses.py
backend/entities/office_hours/ticket_entity.py
backend/models/pagination.py
backend/services/office_hours/__init__.py
backend/services/office_hours/office_hours_statistics.py
backend/services/office_hours/ticket.py
backend/test/services/office_hours/fixtures.py
backend/test/services/office_hours/office_hours_statistics_test.py
backend/test/services/office_hours/office_hours_test.py

This pull request implements the API and necessary models to retrieve paginated tickets for a course site. This data will be ultimately shown in the new "statistics" view for courses.
1. Run the backend tests as outlined in the [testing doc](https://github.com/unc-csxl/csxl.unc.edu/blob/main/docs/testing.md) and confirm that all tests are passing.
2. On the local server, auth as Ina Instructor.
3. Go to the profile page and copy the bearer token.
4. Open the `localhost:1560/docs` page. 
5. Find the API route for statistics. It should be under the "My Courses" tag with the route `/{course_site_id}/statistics/ticket-history`.
6. Ensure that the API route returns the correct tickets based on any combination of date range, student ID, and staff ID filters.
- Note that student IDs and staff …

Task/710-ticket-history: Implement Ticket History 

---

frontend/src/app/my-courses/widgets/office-hours-statistics-card/office-hours-statistics-card.widget.html
frontend/src/styles/styles.scss

This PR modifies the Material styling for the summary page to work better with dark mode.
In addition, this PR also includes a site-wide fix for the button text color in dark mode. Before, text on secondary and tertiary buttons were white rather than the `on-secondary` and `on-tertiary` colors respectively, creating bad contrast. This has now been fixed.
*Closes #728*

(fix:728) Fix Dark Mode Styling Issue Summary Page and Dark Mode Buttons Sitewide

---

backend/api/academics/my_courses.py
backend/entities/office_hours/ticket_entity.py
backend/models/office_hours/ticket.py
backend/services/office_hours/office_hours_statistics.py
backend/test/services/office_hours/office_hours_statistics_test.py
frontend/src/app/my-courses/course/statistics/statistics.component.html
frontend/src/app/my-courses/course/statistics/statistics.component.ts
frontend/src/app/my-courses/my-courses.service.ts

This pull request adds functionality so that staff of a course are able to download office hours data for a course in CSV format. This data includes the students names, the staff member that called the ticket, the ticket type and description, and details about when the ticket was opened, called, and closed (as well as helpful calculations for the wait time and help time, in minutes).
One new backend service method and API were added. The service method is tested with 100% coverage.
*Closes #723*

(task:723) Implement Ticket Data Export to CSV

---

backend/entities/office_hours/ticket_entity.py
backend/models/academics/my_courses.py
frontend/src/app/my-courses/course/statistics/statistics.component.html
frontend/src/app/my-courses/course/statistics/statistics.component.ts
frontend/src/app/my-courses/dialogs/ticket-details/ticket-details.dialog.css
frontend/src/app/my-courses/dialogs/ticket-details/ticket-details.dialog.html
frontend/src/app/my-courses/dialogs/ticket-details/ticket-details.dialog.ts
frontend/src/app/my-courses/my-courses.model.ts
frontend/src/app/my-courses/my-courses.module.ts

This PR implements the ticket details dialog, which allows users to see further information about tickets listed on the Office Hours Statistics Page.
1. Navigate to the OH Statistics page.
2. Click the hamburger menu to the right of one of the past ticket list items.
3. A dialog should appear as shown below.
> _Resolves #722_

Task/722-ticket-dialog: Create Ticket Details Dialog

---

backend/services/signage.py
frontend/src/app/signage/widgets/occupancy/occupancy.widget.html

This PR is for a hotfix of signage. It switches the office hours to correctly display course codes, removes display of past events, and switches the title of current occupancy to "SN156 Availability"
All changes were tested on the frontend via "inspection".

Signage Hotfix

---

backend/models/pagination.py

This hotfix ensures that filters applied to tickets do not get overwritten on page changes. Turns out this was caused because the correct pagination parameters did not propagate to the frontend.
*Resolves #743*

(fix:743) Statistics Filter Hotfix

---

backend/models/pagination.py
frontend/src/app/app.component.ts
frontend/src/app/my-courses/course/course.component.ts

This PR adds two hotfixes for the office hours statistics feature.
* Makes the statistics tab visible for UTAs and GTAs of courses.
* Fix the filtering bug mentioned by @aliciabao in #743.
* (also) Fixes an extraneous error that was popping up on office hours pages in the console.
Note: Due to design concerns, this PR will hold off on #753 - we should discuss this in the next meeting.
*Resolves #751*

(task:751) Office Hours Statistics Hotfixes

---

frontend/src/app/event/event-details/event-details.component.html
frontend/src/app/event/event-editor/event-editor.component.html
frontend/src/app/event/widgets/event-card/event-card.widget.html
frontend/src/app/event/widgets/featured-event-card/featured-event-card.widget.html
frontend/src/app/signage/widgets/event-card/event-card.widget.html

This small PR adds markdown support for event descriptions so that user-inputted events can include markdown elements (such as bold and italic text, as well as paragraph spacing).
The signage component has also been updated to show markdownified event descriptions.
*Resolves #757*

(task:757) Add Markdown Support for Event Descriptions

---

frontend/src/app/signage/weather.service.ts

I was passing by the CSXL today and noticed that the weather icon defaulted to sunny even though it was obviously cloudy outside. I opened the Open Mateo API and saw that the weather code was set to 53: Moderate Drizzle. 
Thus, I have widened the scope of the rainy icon to account for different types of drizzle and freezing rain as well.

Rainy Weather Icon Hotfix

---

backend/api/office_hours/ticket.py
backend/entities/office_hours/ticket_entity.py
backend/models/academics/my_courses.py
backend/models/office_hours/ticket.py
backend/services/office_hours/ticket.py
backend/test/services/office_hours/office_hours_data.py
backend/test/services/office_hours/ticket_test.py
frontend/src/app/my-courses/course/office-hours/office-hours-queue/office-hours-queue.component.ts
frontend/src/app/my-courses/course/office-hours/widgets/close-ticket-dialog/close-ticket.dialog.css
frontend/src/app/my-courses/course/office-hours/widgets/close-ticket-dialog/close-ticket.dialog.html
frontend/src/app/my-courses/course/office-hours/widgets/close-ticket-dialog/close-ticket.dialog.ts
frontend/src/app/my-courses/course/statistics/statistics.component.css
frontend/src/app/my-courses/course/statistics/statistics.component.html
frontend/src/app/my-courses/dialogs/ticket-details/ticket-details.dialog.html
frontend/src/app/my-courses/my-courses.model.ts
frontend/src/app/my-courses/my-courses.module.ts
frontend/src/app/my-courses/my-courses.service.ts
frontend/src/styles/styles.scss

This PR adds the ability for TAs to mark tickets as concerning and to provide notes for later. These notes are also then shown in the summary / ticket history page.
This should not require any migrations - all fields already existed in the entities, just never surfaced. 
When closing a ticket, a dialog now pops up prompting the staff for more information. Once it is filled out, the ticket is closed.
Tickets are marked with a concern badge if a TA has marked the ticket as concerning. 
Notes for tickets are available in the dialog:
* We can add a statistics panel for concerns and filters for this as well.
Tests pass.
*Resolves #689*

(task:689) Ticket Concerns and TA Notes

---

backend/api/academics/my_courses.py
backend/api/office_hours/ticket.py
backend/entities/office_hours/__init__.py
backend/entities/office_hours/course_site_entity.py
backend/entities/office_hours/event_ticket_tags_table.py
backend/entities/office_hours/ticket_entity.py
backend/entities/office_hours/ticket_tag_entity.py
backend/models/academics/my_courses.py
backend/models/office_hours/office_hours_statistics.py
backend/models/office_hours/ticket.py
backend/models/office_hours/ticket_details.py
backend/models/office_hours/ticket_tag.py
backend/models/pagination.py
backend/services/__init__.py
backend/services/academics/course_site.py
backend/services/exceptions.py
backend/services/office_hours/__init__.py
backend/services/office_hours/office_hours_statistics.py
backend/services/office_hours/ticket.py
backend/services/office_hours/ticket_tag.py
backend/test/services/office_hours/fixtures.py
backend/test/services/office_hours/office_hours_data.py
backend/test/services/office_hours/office_hours_statistics_test.py
backend/test/services/office_hours/ticket_tag_test.py
backend/test/services/office_hours/ticket_test.py

This PR implements the ticket tags backend.
- Created the `OfficeHoursTicketTagEntity` and the corresponding association table `event_ticket_tags_table`.
- Created the backend service and API routes for creating, updating, deleting, and retrieving ticket tags for a course site.
- Modified the service methods for filtering tickets and closing tickets to account for ticket tags.
- Added unit tests for the backend services.
> Resolves #768

Task/768-ticket-tags-backend: Implement Ticket Tags Backend

---

backend/api/authentication.py

This small change in the authentication logic allows other web projects in a local environment to simulate the UNC Shibboleth SSO authentication using the CSXL server without a proxy set up in CloudApps.
The fix was to allow the set `origin` to propagate through in the `http` route in the redirect call for handing authentication on the production server. This allows for other URL prefixes (for example in my case w/ a Next.js project, `localhost:3000/api/`) to be used in place of the hard-coded `localhost:1560/` for connecting to authentication logic.
Changing this code in the local environment does not break the authentication workflow.
@KrisJordan are there any security concerns with this or are we good to merge?

chore: Allow Other Apps to use CSXL Server as UNC SSO Auth Proxy

---

backend/api/authentication.py

This PR changes the authentication logic to remove the `/auth` suffix after the origin redirect. Before this modification, since the `/auth` suffix was attached to the origin, other backends using the CSXL site as a UNC auth proxy had to implement their auth API endpoint route to have `/auth` as a suffix.
For example, the CSXL site implements the authentication route as `localhost:1560/auth` (where `origin="localhost:1560"`), while a Next.js site might have implemented the route as `localhost:3000/api/auth` (where `origin="localhost:3000"`). Both are valid, but only because the routes end with `/auth`.
There are use cases where a backend might want to connect to multiple auth providers with a route something like `localhost:8000/api/auth/unc` along with another route …

chore(auth)!: allow for more flexible auth proxy use

---

backend/services/academics/course_site.py

The previous PR added a sort by role, then section #. This PR adds a third-level sort for last name within each section.

chore(office-hours): add third sort for roster by last name

---

backend/services/office_hours/office_hours_statistics.py

Adds sorting to the statistics filter options so that students and staff are listed in alphabetical order.

fix(office-hours): add sorting to statistics filter options

---

frontend/src/app/my-courses/course/office-hours/office-hours-page/office-hours-page.component.css
frontend/src/app/my-courses/course/office-hours/office-hours-page/office-hours-page.component.html

Fixes the styling of future office hours action buttons from this:
to this:
and on dark mode:

fix(office-hours): fix styling of future event action buttons

---

frontend/src/styles/styles.scss

The current table divider color is a bit too jarring and does not fit with the other outline colors on the site. This PR makes the table divider colors the same as a card or table outline color, like so:
**Light mode**:
from:
to:
**Dark mode:**
from:
to:

fix: soften table row divider color

---

frontend/src/app/navigation/navigation.component.html
frontend/src/styles/styles.scss

This PR updates the prominence of the loading bar for network requests. For very quick requests now, nothing shows up (since the background color of the loading bar has changed to match the site background). For slower requests, the loading bar is a secondary color.

chore: update loading bar color prominence

---

frontend/package-lock.json

Somewhere along the line, the node modules either updated or some got removed, so this hot fix attempts to add it back. Both the previous PR and the new one work in the local production.

fix: revert to old package lock
