docs/auth.md, docs/get_started.md
First pass on addressing authentication and authorization concerns across both frontend and backend.
=> Progress on auth docs

backend/api/authentication.py, docs/auth.md, docs/get_started.md
This feature branch had prior PRs (#26, #24).
To make the documentation more meaningful, some code wound up being refactored in #24.
This PR closes #13
=> Add documentation for authentication and authorization.

backend/api/organizations.py, backend/main.py, backend/test/services/organization/organization_demo_data.py
This pull request adds a description for the Organization API routes, moves the Admin routes to the bottom of the page, and re-orders the demo data to be in alphabetical order.
Ran `honcho start` and visited the /docs route to make sure the changes worked.
=> Update api docs

backend/api/organizations.py
Small fix to tags that got mis-edited in another PR
=> Fix API doc tag

frontend/src/app/navigation/navigation.service.ts
When navigating between areas of the site there were previously a significant number of "[change made after detect](organization-page.component.html:12 ERROR Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'. Find more at https://angular.io/errors/NG0100)" errors.
This has to do with the interplay of the navigation component, the HTTP intercepter updating state based on the status of async HTTP requests, and the change detection cycles of angular. The solution presented in this PR feels more like an acceptable workaround, delaying state update pushes to the next event cycle tick, but could use further investigation in the future. There do not seem to be any significant downsides to this …
=> Fix changes after change detection cycle error

frontend/src/app/organization/widgets/organization-details-info-card/organization-details-info-card.widget.css, frontend/src/app/shared/event-list/event-list.widget.html
This PR fixes two visual bugs in the latest release.
- Fixed font size of the Organization Detail page from increasing when on a wide enough monitor.
- Add a short sentence to indicate when there are no upcoming events.
=> Fix Frontend Visual Bugs in Production

docs/widgets.md
Fixes image references in the widget reading.
=> Update Widget Reading to Contain New Links

backend/api/events.py, backend/services/event.py, backend/test/services/event/event_test.py, frontend/src/app/event/event.service.ts, frontend/src/app/organization/organization-details/organization-details.component.ts, frontend/src/app/organization/organization.resolver.ts
=> Port Organization Details Crash Fix

docs/widgets.md
=> Change `onJoinButtonPressed` to `joinButtonPressed` in Reading

frontend/src/app/about/about.component.html, frontend/src/app/admin/roles/details/admin-role-details.component.html, frontend/src/app/admin/roles/list/admin-roles-list.component.html, frontend/src/app/coworking/ambassador-home/ambassador-home.component.html, frontend/src/app/coworking/widgets/coworking-reservation-card/coworking-reservation-card.html, frontend/src/app/coworking/widgets/dropin-availability-card/dropin-availability-card.widget.html, frontend/src/app/coworking/widgets/operating-hours-panel/operating-hours-panel.widget.html, frontend/src/app/event/event-editor/event-editor.component.css, frontend/src/app/event/event-editor/event-editor.component.html, frontend/src/app/organization/organization-editor/organization-editor.component.css, frontend/src/app/organization/organization-editor/organization-editor.component.html, frontend/src/app/organization/widgets/organization-card/organization-card.widget.html, frontend/src/app/organization/widgets/organization-details-info-card/organization-details-info-card.widget.html, frontend/src/app/profile/profile-editor/profile-editor.component.css, frontend/src/app/profile/profile-editor/profile-editor.component.html, frontend/src/styles.scss
This PR changes the frontend Angular Material styles of the application.
- Migrated all Material Cards to use the outline style.
- Migrated all Material Buttons to use the stroked style.
- Migrated all Material Input Fields to use the outline style.
- The Coworking Operating Hours widget uses an expansion panel - this does not have the ability to change to a different style! @KrisJordan, any thoughts on potentially using a different Angular element here?
=> Migrate CSXL Application to Cohesive Design

docs/widgets.md
=> Add Code File Labels and some Clarification to Event Binding Section

.devcontainer/devcontainer.json, README.md, docs/branches.md, docs/database.md, docs/get_started.md
The documentation for database concerns and best practices of branching, pull requesting, and merging is insufficient in the CSXL repository. This PR improves upon this.
=> Improve documentation of database and branching practices

frontend/src/app/event/event-editor/event-editor.component.html, frontend/src/app/event/event-editor/event-editor.component.ts, frontend/src/app/event/event-filter/event-filter.pipe.ts
This pull request fixes major issues with how dates worked on the Event frontend of the CSXL application.
- Fixed error where the "edit date" field for an event would not show the correct time upon editing.
- Fixed error where dates sometimes would display correctly.
- Re-fix error where past events would show on the events page.
- These errors were fixed by using the DatePipe to convert dates to the exact format that `matInput` expects for dates.
- These features were tested on the frontend using `honcho start`.
*This PR resolves #134*
=> Resolve Date Time Issues

backend/api/events.py, backend/services/event.py, backend/services/user.py, backend/test/services/event/event_test.py, backend/test/services/fixtures.py, backend/test/services/user_test.py
This PR is a WIP that targets changes to the Event Registration Backend features.
=> Modifications to the event registration feature PR

backend/api/events.py, backend/entities/event_registration_entity.py, backend/entities/user_entity.py, backend/models/user_details.py, backend/services/event.py, backend/test/services/event/event_test.py
I'm moving forward with refactoring how to approach UserDetails / registrations @ajaygandecha
=> Refactor user registrations to live separate from UserDetails

docs/sqlalchemy/2_entities.md
This PR adds an important point to the entities docs mentioned by @KrisJordan in #173 that I forgot to fix in #174.
=> Add Important Point to Entities Docs

frontend/src/app/profile/profile-editor/profile-editor.component.css, frontend/src/app/profile/profile-editor/profile-editor.component.html, frontend/src/app/profile/profile-editor/profile-editor.component.ts
- Minor fix, when a user is on light-mode, the color of their github link is set to black so it is viewable!
=> Fix Github Link on Light Mode

backend/entities/courses/course_entity.py, backend/entities/courses/section_entity.py, backend/entities/courses/term_entity.py, backend/models/courses/__init__.py, backend/models/courses/course.py, backend/models/courses/course_details.py, backend/models/courses/section.py, backend/models/courses/section_details.py, backend/models/courses/section_staff.py, backend/models/courses/term.py, backend/models/courses/term_details.py
This major pull request makes progress on adding all of the necessary models for the courses feature to function. This includes including courses, terms (semesters), course sections, and the necessary details models to store relationships.
=> Create Models for Course Feature

backend/api/courses/course.py, backend/api/courses/section.py, backend/api/courses/term.py, backend/main.py, backend/script/reset_demo.py
This major pull request implements APIs for the courses feature.
The following APIs have been added based on the service functions merged from #196 .
* **GET** `/api/terms/` -> Returns all terms.
* **GET** `/api/terms/:id` -> Returns a term.
* **GET** `/api/terms/current` -> Returns the current term.
* **POST** `/api/terms/` -> Create a new term.
* **PUT** `/api/terms/` -> Update a term.
* **DELETE** `/api/terms/` -> Delete a term.
* **GET** `/api/courses/` -> Returns all courses.
* **GET** `/api/courses/:id` -> Returns course for a given ID.
* **GET** `/api/courses/:subject_code/:number` -> Returns one course.
* **POST** `/api/courses/` -> Create a new course.
* **PUT** `/api/courses/` -> Update a course.
* **DELETE**  `/api/courses/` -> Delete a course.
* **GET** `/api/sections/` -> …
=> Create APIs for Course Feature

backend/entities/event_registration_entity.py, backend/models/event_member.py, backend/services/event.py, frontend/src/app/event/event-editor/event-editor.component.html, frontend/src/app/event/event-editor/event-editor.component.ts, frontend/src/app/event/event.model.ts, frontend/src/app/event/widgets/event-detail-card/event-detail-card.widget.css, frontend/src/app/event/widgets/event-detail-card/event-detail-card.widget.html, frontend/src/app/event/widgets/event-detail-card/event-detail-card.widget.ts, frontend/src/app/event/widgets/event-users-list/event-users-list.widget.html, frontend/src/app/event/widgets/event-users-list/event-users-list.widget.ts
This PR improves the UI/UX as it relates to Event Organizers by fixing the Github avatar bug, adding Event Organizers to the Event Details card, removing them from the registrations list, and fixing the Event Organizer form control on the Event Editor form so it properly implements the remove organizers button.
> This PR resolves issue #233.
=> Event Organizer Fixes #233

frontend/src/app/event/widgets/event-detail-card/event-detail-card.widget.css, frontend/src/app/event/widgets/event-detail-card/event-detail-card.widget.html
This PR fixes the styling issues with the organizer chip avatars on the Event Details card. It also adds a scroll bar to the event details card so information is still viewable if the text overflows the card.
=> Improve Event Detail Card Styling

frontend/src/app/event/event-editor/event-editor.component.html, frontend/src/app/event/event-editor/event-editor.component.ts, frontend/src/app/organization/organization-editor/organization-editor.component.html, frontend/src/app/organization/organization-editor/organization-editor.component.ts
This branch adds "CANCEL" buttons to the organization editor page and the event editor page to return the user to the previous screen.
=> 240 - Add Cancel Button to Organization/Event Editor Components

backend/entities/academics/section_entity.py, backend/entities/academics/section_member_entity.py, backend/entities/office_hours/__init__.py, backend/entities/office_hours/oh_event_entity.py, backend/entities/office_hours/oh_section_entity.py, backend/entities/office_hours/oh_ticket_entity.py, backend/entities/office_hours/user_created_tickets_table.py, backend/entities/room_entity.py, backend/models/office_hours/oh_type.py, backend/models/office_hours/ticket_state.py, backend/models/office_hours/ticket_type.py
Table and Entities for Office Hours. 
https://miro.com/app/board/uXjVNwL9kIo=/
=> 281 Create Office Hours Entities

frontend/src/app/coworking/room-reservation/new-reservation-page/new-reservation-page.component.css, frontend/src/app/coworking/room-reservation/new-reservation-page/new-reservation-page.component.html, frontend/src/app/coworking/widgets/room-reservation-table/room-reservation-table.widget.html
Enables horizontal scrolling for mobile devices.
Fixes minor issue in room reservation table widget.
=> 263 modify new reservation page

backend/entities/academics/section_member_entity.py, backend/entities/office_hours/oh_event_entity.py, backend/entities/office_hours/oh_section_entity.py, backend/entities/office_hours/oh_ticket_entity.py, backend/entities/room_entity.py, backend/models/academics/section_member_details.py, backend/models/office_hours/oh_event.py, backend/models/office_hours/oh_event_details.py, backend/models/office_hours/oh_section_details.py, backend/models/office_hours/oh_ticket.py, backend/models/office_hours/oh_ticket_details.py, backend/models/room_details.py
Branch title is misleading... we initially wanted to start on services and decided to complete the to_model and from_model methods in all our entity classes first. 
- edited to_details_model in section_member_entity and room_entity to reflection relations
- created section_member_details model to reflect relations for ticket information
- fixed import statements in various model files
=> 279 add oheventservice  corresponding methods

frontend/src/app/coworking/ambassador-home/ambassador-home.component.css, frontend/src/app/coworking/ambassador-home/ambassador-home.component.html, frontend/src/app/coworking/coworking-home/coworking-home.component.css, frontend/src/app/coworking/coworking-home/coworking-home.component.html, frontend/src/app/coworking/coworking-home/coworking-home.component.ts, frontend/src/app/coworking/coworking.module.ts, frontend/src/app/coworking/coworking.service.ts, frontend/src/app/coworking/reservation/reservation.component.css, frontend/src/app/coworking/room-reservation/confirm-reservation/confirm-reservation.component.css, frontend/src/app/coworking/room-reservation/confirm-reservation/confirm-reservation.component.html, frontend/src/app/coworking/room-reservation/confirm-reservation/confirm-reservation.component.ts, frontend/src/app/coworking/room-reservation/new-reservation-page/new-reservation-page.component.css, frontend/src/app/coworking/room-reservation/new-reservation-page/new-reservation-page.component.html, frontend/src/app/coworking/room-reservation/new-reservation-page/new-reservation-page.component.ts, frontend/src/app/coworking/room-reservation/reservation-table.service.ts, frontend/src/app/coworking/room-reservation/room-reservation.service.ts, frontend/src/app/coworking/rx-coworking-status.ts, frontend/src/app/coworking/widgets/coworking-reservation-card/coworking-reservation-card.css, frontend/src/app/coworking/widgets/coworking-reservation-card/coworking-reservation-card.html, frontend/src/app/coworking/widgets/coworking-reservation-card/coworking-reservation-card.ts, frontend/src/app/coworking/widgets/date-selector/date-selector.widget.ts, frontend/src/app/coworking/widgets/dropin-availability-card/dropin-availability-card.widget.css, frontend/src/app/coworking/widgets/operating-hours-dialog/operating-hours-dialog.widget.css, frontend/src/app/coworking/widgets/operating-hours-dialog/operating-hours-dialog.widget.html, frontend/src/app/coworking/widgets/operating-hours-panel/operating-hours-panel.widget.css, frontend/src/app/coworking/widgets/operating-hours-panel/operating-hours-panel.widget.html, frontend/src/app/coworking/widgets/room-reservation-table/room-reservation-table.widget.css, frontend/src/app/coworking/widgets/room-reservation-table/room-reservation-table.widget.html, frontend/src/app/coworking/widgets/room-reservation-table/room-reservation-table.widget.ts
- Introduced more compact card designs across various components for consistency.
- Relocated Coworking Reservation cards to the Coworking Home for better visibility.
- Implemented refresh functionality for Upcoming Room Reservations.
- Added an accordion-style toggle for action buttons on reservations with a "CONFIRMED" status.
- Addressed and corrected padding discrepancies in the Coworking-Home component.
- Redundant text removed to streamline the interface, specifically the "Who" section.
- Padding has been reduced for a more compact look.
- Active reservations are filtered out to maintain focus on truly upcoming bookings.
- Previously displayed on the New Reservation Component that hosts the table widget.
- Now displays on the Coworking Home view under a section called "Upcoming …
=> 260 migrate upcoming reservations up a level into coworking

frontend/src/app/academics/academics-admin/course/course-editor/course-editor.component.html, frontend/src/app/academics/academics-admin/room/room-editor/room-editor.component.html, frontend/src/app/academics/academics-admin/section/section-editor/section-editor.component.html, frontend/src/app/academics/academics-admin/term/term-editor/term-editor.component.html, frontend/src/app/event/event-editor/event-editor.component.html, frontend/src/app/organization/organization-editor/organization-editor.component.html, frontend/src/app/organization/widgets/organization-card/organization-card.widget.html, frontend/src/app/profile/profile-editor/profile-editor.component.html
This small PR fixes casing on words in buttons throughout the CSXL site to be more consistent. Most of the buttons used proper case rather than uppercase, so this commit changes some of the final remaining uppercased buttons to proper case.
=> Fix Button Casing Throughout CSXL Site

frontend/src/app/coworking/room-reservation/new-reservation-page/new-reservation-page.component.css, frontend/src/app/coworking/room-reservation/new-reservation-page/new-reservation-page.component.html, frontend/src/app/coworking/widgets/date-selector/date-selector.widget.html, frontend/src/app/coworking/widgets/room-reservation-table/room-reservation-table.widget.css, frontend/src/app/coworking/widgets/room-reservation-table/room-reservation-table.widget.html
This pull request makes UI modifications to the amazing new Room Reservation Feature to conform to the CSXL site's current Material UI usage and standards.
- Embedded the main page into a card component, using the outlined style, with a title.
- Right-aligned the date picker to make room for the title, and update the date picker to use the outlined style.
- Modified the save / reserve button to use the outlined style.
- Rounded the square color key items in the legend.
- Removed the "Total Hours Remaining" label (if we want to add this back, no problem! I think we would need to find a good placement for it though)
=> Conform Room Reservation Feature to CSXL's Material UI Conventions

frontend/src/app/navigation/navigation.component.html
This PR will build upon and improve the Sidebar buttons for the CSXL Slack and GitHub created in #239 and updated in #272.
- Added Instagram button to `Navigation` component
=> Instagram sidebar button

frontend/package-lock.json
Resolves a few security CVEs, remaining concerns are in development mode / build process, not in production.
=> Fix low-hanging vulnerabilities

frontend/src/app/shared/profile-about-card/profile-about-card.widget.css, frontend/src/app/shared/profile-about-card/profile-about-card.widget.html
Fix styling issues with profile card when profile is linked to Github.
=> Fix Profile Card Styling

backend/services/coworking/policy.py
Temporarily block off rooms for furniture installation
=> Update policy for furniture install

backend/services/coworking/policy.py, frontend/src/app/coworking/widgets/dropin-availability-card/dropin-availability-card.widget.ts
Temporary hack for blocking off the communal area of the XL for use in office hours and preventing reservations on hallway rooms.
=> Prevent communal area drop-ins while furniture installation completes

frontend/src/app/profile/profile-page/profile-page.component.css, frontend/src/app/profile/profile-page/profile-page.component.html
Update profile page to ensure that the cards dynamically change width based on screen size.
=> Make Profile Page Responsive

backend/services/coworking/policy.py, frontend/src/app/coworking/widgets/dropin-availability-card/dropin-availability-card.widget.ts
Now that the installation work for the hallway has completed, we are reopening rooms for reservation!
=> Reset policies for Phase 2 Launch of XL

frontend/src/app/academics/academics.resolver.ts, frontend/src/app/academics/academics.service.ts
This PR is a hotfix changing the Term code from F24 -> 24F
=> TA Application Hotfix

backend/api/coworking/reservation.py, backend/services/coworking/policy.py, backend/services/coworking/reservation.py, backend/test/services/coworking/operating_hours_data.py, backend/test/services/coworking/policy_test.py, backend/test/services/coworking/reservation/change_test.py, backend/test/services/coworking/reservation/draft_test.py, backend/test/services/coworking/reservation/get_current_reservations_for_user_test.py, backend/test/services/coworking/reservation/get_map_current_reservations_test.py, backend/test/services/coworking/reservation/get_total_time_user_reservations_test.py, backend/test/services/coworking/reservation/list_all_active_and_upcoming_test.py, backend/test/services/coworking/reservation/reservation_data.py, backend/test/services/room_data.py
This PR addresses the longstanding issue of incomplete documentation and test coverage present in the backend for the room reservation feature. 
In general, I made sure that each method that we implemented in the backend has a corresponding test which covers the various cases that could arise while running a method.
Also, I worked on changing the docstrings wherever I saw rooms for improvement to better document the code that we wrote.
=> 100% Test Coverage for Room Reservations

backend/api/application.py, backend/models/application.py, backend/services/application.py, frontend/src/app/academics/academics.service.ts
This PR adds a temporary API to get TA Applications for a section.
=> Add API for getting Applications for a Section

frontend/src/app/academics/academics-home/academics-home.component.html, frontend/src/app/academics/course-catalog/course-catalog.component.css, frontend/src/app/academics/course-catalog/course-catalog.component.html, frontend/src/app/academics/section-offerings/section-offerings.component.css, frontend/src/app/academics/section-offerings/section-offerings.component.html, frontend/src/app/event/event-page/event-page.component.html, frontend/src/app/shared/banner-card/banner-card.component.css, frontend/src/app/shared/banner-card/banner-card.component.ts, frontend/src/app/ta-application/uta-application/uta-application.component.css, frontend/src/app/ta-application/uta-application/uta-application.component.html
This preliminary pull request refactors the academics feature to use Material 3.
This pull request has been made for my review only, then it will be merged into the feature branch.
*Closes #476*
=> Upgrade Academics Feature to use Material 3

frontend/src/app/profile/profile-editor/profile-editor.component.css, frontend/src/app/profile/profile-editor/profile-editor.component.html, frontend/src/app/profile/profile-page/profile-page.component.css, frontend/src/app/profile/profile-page/profile-page.component.html, frontend/src/app/shared/profile-about-card/profile-about-card.widget.css, frontend/src/app/shared/profile-about-card/profile-about-card.widget.html
This preliminary pull request refactors the profile page to use Material 3.
This pull request has been made for my review only, then it will be merged into the feature branch.
More work has to be done here, and will be done in #484.
*Closes #474*
=> Upgrade Profile Feature to use Material 3

frontend/src/app/coworking/coworking-home/coworking-home.component.css, frontend/src/app/coworking/coworking-home/coworking-home.component.html, frontend/src/app/coworking/coworking.module.ts, frontend/src/app/coworking/room-reservation/confirm-reservation/confirm-reservation.component.ts, frontend/src/app/coworking/room-reservation/new-reservation-page/new-reservation-page.component.css, frontend/src/app/coworking/room-reservation/new-reservation-page/new-reservation-page.component.html, frontend/src/app/coworking/widgets/coworking-reservation-card/coworking-reservation-card.css, frontend/src/app/coworking/widgets/coworking-reservation-card/coworking-reservation-card.html, frontend/src/app/coworking/widgets/coworking-reservation-card/coworking-reservation-card.ts, frontend/src/app/coworking/widgets/dropin-availability-card/dropin-availability-card.widget.css, frontend/src/app/coworking/widgets/dropin-availability-card/dropin-availability-card.widget.html, frontend/src/app/coworking/widgets/operating-hours-panel/operating-hours-panel.widget.css, frontend/src/app/coworking/widgets/operating-hours-panel/operating-hours-panel.widget.html, frontend/src/app/coworking/widgets/reservation-facts/reservation-facts.widget.css, frontend/src/app/coworking/widgets/reservation-facts/reservation-facts.widget.html, frontend/src/app/coworking/widgets/reservation-facts/reservation-facts.widget.ts, frontend/src/styles/styles.scss
This preliminary pull request refactors the coworking page to use Material 3.
This pull request has been made for my review only, then it will be merged into the feature branch.
More work has to be done here, and will be done in #487.
*Closes #473*
=> Upgrade Coworking Feature to use Material 3

frontend/src/app/coworking/ambassador-home/ambassador-room/list/ambassador-room-list.component.css, frontend/src/app/coworking/ambassador-home/ambassador-room/list/ambassador-room-list.component.html, frontend/src/app/coworking/ambassador-home/ambassador-xl/list/ambassador-xl-list.component.css, frontend/src/app/coworking/ambassador-home/ambassador-xl/list/ambassador-xl-list.component.html, frontend/src/app/coworking/widgets/coworking-reservation-card/coworking-reservation-card.html
This preliminary pull request refactors the XL ambassador page to use Material 3.
This pull request has been made for my review only, then it will be merged into the feature branch.
More work has to be done here, and will be done in #487.
*Closes #491*
=> Upgrade Ambassador Feature to use Material 3 

.devcontainer/Dockerfile, Dockerfile, static/.gitignore
Summer refresh is underway with updating our dependencies!
=> Upgrade to Node v22

backend/entities/academics/section_entity.py, backend/models/academics/section.py, backend/services/academics/section_member.py, backend/test/services/academics/section_data.py, frontend/src/app/academics/academics.models.ts, frontend/src/app/academics/academics.resolver.ts, frontend/src/app/my-courses/catalog/section-offerings/section-offerings.component.html, frontend/src/app/my-courses/catalog/section-offerings/section-offerings.component.ts, frontend/src/app/my-courses/course/office-hours/office-hours-get-help/office-hours-get-help.component.html, frontend/src/app/my-courses/course/office-hours/office-hours-get-help/office-hours-get-help.component.ts, frontend/src/app/my-courses/my-courses-page/my-courses-page.component.html, frontend/src/app/my-courses/widgets/course-card/course-card.widget.html, frontend/src/app/my-courses/widgets/course-card/course-card.widget.scss
This pull request includes some hotfixes that fix some issues in the deployment of the My Courses feature.
* Add enrollment and instructor information to the Section Catalog view.
* Remove the disabled Join button on the My Courses page.
* Add better labeling of meeting patterns for sections on course site cards.
* Fix the Read CSV function to import students into classes.
* Fix the office hours ticket creation.
=> My Courses Patch

frontend/src/app/app.module.ts, frontend/src/app/my-courses/catalog/catalog.component.ts, frontend/src/app/my-courses/catalog/course-catalog/course-catalog.component.ts, frontend/src/app/my-courses/course/course.component.ts, frontend/src/app/my-courses/course/office-hours/office-hours-editor/office-hours-editor.component.html, frontend/src/app/my-courses/course/office-hours/office-hours-editor/office-hours-editor.component.ts, frontend/src/app/my-courses/course/office-hours/office-hours-get-help/office-hours-get-help.component.ts, frontend/src/app/my-courses/course/office-hours/office-hours-page/office-hours-page.component.ts, frontend/src/app/my-courses/course/office-hours/office-hours-queue/office-hours-queue.component.ts, frontend/src/app/my-courses/course/roster/roster.component.ts, frontend/src/app/my-courses/widgets/course-card/course-card.widget.html, frontend/src/app/navigation/navigation.component.css, frontend/src/app/navigation/navigation.component.html, frontend/src/app/profile/profile-page/profile-page.component.ts, frontend/src/app/shared/community-agreement/community-agreement.widget.css, frontend/src/app/shared/community-agreement/community-agreement.widget.html, frontend/src/app/shared/community-agreement/community-agreement.widget.ts, frontend/src/app/shared/shared.module.ts, frontend/src/styles/styles.scss
PR makes the following changes:
* Try to add rounded corners for profile images (there is no way to test this on localhost, so hoping for the best ...)
* Redesign the Community Agreement dialog page to conform to M3 standards.
* Fix the Office Hours Editor start time issue.
=> Styling Changes and My Courses Hotfix

frontend/src/app/navigation/navigation.component.css, frontend/src/app/navigation/navigation.component.html
This very small PR fixes the alignment of the profile icons on the navbar on mobile devices.
=> Fix Profile Icons on Mobile

CONTRIBUTING.md
Hey @KrisJordan / @jadekeegan / @atoneyd - in preparation for COMP 423 and the new CSXL site upgrades, I wanted to revisit the #440 ticket and create a list of meaningful contributing guidelines for the repo! Contributing Guidelines docs are a feature of GitHub and should appear as a tab next to the README and LICENSE on the front page of the CSXL site:
Please let me know what you think and feel free to modify / contribute anything here! Most of the text in this doc was repurposed from an issue written in May.
Edit: Since the document might be hard to find, try viewing it [here](https://github.com/unc-csxl/csxl.unc.edu/blob/f2e866a589171db40ca3acf4624c2b7a075749b2/CONTRIBUTING.md).
=> Write Contributing Guidelines

.devcontainer/devcontainer.json, backend/entities/academics/hiring/application_review_entity.py, backend/models/academics/hiring/application_review.py, frontend/.eslintrc.json, frontend/src/app/hiring/hiring-admin/hiring-admin.component.html, frontend/src/app/hiring/hiring-page/hiring-page.component.css, frontend/src/app/hiring/hiring-page/hiring-page.component.html, frontend/src/app/hiring/hiring.service.ts, frontend/src/app/hiring/widgets/application-card/application-card.widget.html, frontend/src/app/hiring/widgets/course-hiring-card/course-hiring-card.widget.html
Improvements in this PR include:
- Add e-mail to CSV Export
- Add indicator of COMP227 in roster
- Minor text changes
- Link to course site hiring page from hiring page
- Turn off autoformatting of angular HTML files
=> Hiring feature improvements

backend/api/academics/hiring.py, backend/models/academics/hiring/hiring_assignment.py, backend/services/academics/hiring.py, frontend/src/app/hiring/dialogs/create-assignment-dialog/create-assignment.dialog.html, frontend/src/app/hiring/dialogs/create-assignment-dialog/create-assignment.dialog.ts, frontend/src/app/hiring/dialogs/edit-assignment-dialog/edit-assignment.dialog.html, frontend/src/app/hiring/dialogs/edit-assignment-dialog/edit-assignment.dialog.ts, frontend/src/app/hiring/dialogs/quick-create-assignment-dialog/quick-create-assignment.dialog.html, frontend/src/app/hiring/dialogs/quick-create-assignment-dialog/quick-create-assignment.dialog.ts, frontend/src/app/hiring/hiring-admin/hiring-admin.component.html, frontend/src/app/hiring/hiring.models.ts, frontend/src/app/hiring/hiring.service.ts, frontend/src/app/hiring/widgets/course-hiring-card/course-hiring-card.widget.html, frontend/src/app/hiring/widgets/course-hiring-card/course-hiring-card.widget.ts
This PR adds support for making hiring assignments back to the system.
=> Hotfix hiring for rostering management

backend/entities/academics/hiring/hiring_assignment_entity.py, backend/entities/application_entity.py, backend/models/application.py, backend/services/application.py, frontend/src/app/applications/applications.model.ts, frontend/src/app/applications/form/application-form.component.css, frontend/src/app/applications/form/application-form.component.html, frontend/src/app/applications/form/application-form.component.ts, frontend/src/app/hiring/hiring.models.ts
This pull request enables TA applicants to see their assignment on the morning of 8/18/2024.
=> Add Assignment Notification to Application Page

backend/entities/academics/hiring/hiring_assignment_entity.py, backend/models/academics/hiring/hiring_assignment.py, frontend/src/app/hiring/hiring-summary/hiring-summary.component.html, frontend/src/app/hiring/hiring-summary/hiring-summary.component.ts, frontend/src/app/hiring/hiring.models.ts
This PR adds a Course column to the HR Onboarding screen for TA hiring. It also condenses the name/PID column.
=> Add course to onboarding HR screen

frontend/src/app/navigation/navigation.component.css, frontend/src/app/navigation/navigation.component.html, frontend/src/app/navigation/navigation.component.ts, frontend/src/styles/styles.scss
This PR adds the CSXL Instagram and GitHub to the sidebar for easy access.
=> Add Instagram and GitHub to the Sidebar

frontend/src/app/my-courses/catalog/course-catalog/course-catalog.component.html, frontend/src/app/my-courses/catalog/section-offerings/section-offerings.component.html
This small PR fixes the wide overflow on the tables in the section offerings and course catalogs tables.
=> Fix Overflow on Catalog Tables

frontend/src/app/event/events-page/events-page.component.css, frontend/src/app/hiring/hiring-preferences/hiring-preferences.component.css, frontend/src/app/hiring/widgets/application-card/application-card.widget.css, frontend/src/app/navigation/navigation.component.css, frontend/src/app/navigation/widgets/slack-invite-box/slack-invite-box.widget.css, frontend/src/app/shared/community-agreement/community-agreement.widget.css, frontend/src/app/welcome/welcome-page/welcome-page.component.css, frontend/src/styles/styles.scss
This PR adds global styles across the CSXL scrollbars specifically for Chrome webkit. It also removes scrollbar tracks that appear on cards automatically due to `overflow-y` being set to `scroll`.
> Resolves #602.
=> design/csxl-602: Beautify Site-Wide Scrollbars

backend/services/coworking/policy.py
Update times when rooms are reserved for office hours.
=> Update reserved hours for room scheduling.

frontend/src/app/my-courses/course/office-hours/office-hours-editor/office-hours-editor.component.html, frontend/src/app/my-courses/course/office-hours/office-hours-editor/office-hours-editor.component.ts, frontend/src/app/my-courses/course/office-hours/office-hours-get-help/office-hours-get-help.component.html, frontend/src/app/my-courses/course/office-hours/office-hours-get-help/office-hours-get-help.component.ts, frontend/src/app/my-courses/course/office-hours/office-hours-queue/office-hours-queue.component.css
This pull request implements the following fixes for the office hours feature:
- The queue is now scrollable to account for ticket overflow.
- The labels "Assignment Help" and "Conceptual Help" now show up correctly in the queue (Resolves #630)
- Adds a validator to the end time for editing office hours events so that the end time must be after the start time (Resolves #610)
=> Office Hours Feature UI Patch

backend/services/application.py
This PR prepares the TA applications for Spring 2025 by moving the application release date to one day after FDOC.
=> Prepare TA Applications for Spring 2025

backend/services/application.py, frontend/src/app/applications/form/application-form.component.ts
Let's try this...
@KrisJordan 🙈
=> Work on Spring 2025 TA Applications

backend/services/academics/term.py, backend/services/application.py, frontend/src/app/academics/academics-admin/term/term-editor/term-editor.component.html, frontend/src/app/academics/academics-admin/term/term-editor/term-editor.component.ts, frontend/src/app/academics/academics.models.ts, frontend/src/app/academics/academics.resolver.ts, frontend/src/app/applications/form/application-form.component.ts
Adds the backend and frontend to edit the application start / end date for terms.
=> Add Application Date Start / End Editor for Terms

backend/services/office_hours/office_hours.py
Thank you @KrisJordan for finding this!
=> Remove Comma That Broke Everything

backend/services/office_hours/office_hours.py, frontend/src/app/admin/admin-routing.module.ts
This small PR should fix the admin page from not showing up for developers.
=> Admin Page Fix

frontend/src/app/applications/form/application-form.component.ts
Off by one strikes again... January, the 0th month!
@ajaygandecha you'll enjoy this one :)
=> Fix month of TA assignment releases

frontend/src/app/my-courses/course/office-hours/widgets/office-hour-event-card/office-hour-event-card.widget.html
=> Add office hours event description to card

backend/services/office_hours/office_hours_statistics.py, frontend/src/app/my-courses/dialogs/ticket-details/ticket-details.dialog.html
Fix ticket length and history sorting.
=> Hotfix: Ticket Statistics

frontend/src/app/app.component.ts, frontend/src/app/my-courses/course/course.component.ts
This small PR ensures that UTAs and GTAs are able to access office hours statistics.
*Resolves #752*
=> (fix:752) Add Statistics Tab Visibility for UTAs and GTAs

backend/api/academics/hiring.py, backend/services/academics/hiring.py, frontend/src/app/hiring/hiring-admin/hiring-admin.component.html, frontend/src/app/hiring/hiring-admin/hiring-admin.component.ts, frontend/src/app/hiring/hiring.module.ts, frontend/src/app/hiring/hiring.service.ts
Add the ability to export all applications for a given academic term. This feature will support some offline backend hiring processes.
Updated the UI of the hiring page to have an actions dropdown rather than individual buttons.
Verified by testing in development. Some concern over memory load required in production, but will test while we are preseason.
=> feat: export all applicants in csv format
